//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC28NowPlayingEpisodeFeatureImpl23NowPlayingEpisodePlayer.h"

@interface _TtC28NowPlayingEpisodeFeatureImpl23NowPlayingEpisodePlayer (NowPlayingEpisodeFeatureImpl2)
- (void)notifyObserversModelDidUpdateWithPosition:(double)arg1 segmentPlayingIndex:(long long)arg2;
- (void)notifyObserversPlayerDidUpdatePositionWithPosition:(double)arg1;
- (void)notifyObserversPlayerDidChangeSegmentWithSegmentIndex:(long long)arg1 startPosition:(double)arg2;
- (void)notifyObserversPlayerStateDidChange;
@end

