//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC23YourLibraryXFeatureImpl28YourLibraryContentViewBinder.h"

#import "UICollectionViewDataSourcePrefetching-Protocol.h"

@interface _TtC23YourLibraryXFeatureImpl28YourLibraryContentViewBinder (YourLibraryXFeatureImpl1) <UICollectionViewDataSourcePrefetching>
- (void)collectionView:(id)arg1 cancelPrefetchingForItemsAtIndexPaths:(id)arg2;
- (void)collectionView:(id)arg1 prefetchItemsAtIndexPaths:(id)arg2;
@end

