//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTFreeTierPlaylistAdditionalCallToAction-Protocol.h"

@protocol SPTFreeTierPlaylistAdditionalCallToActionDelegate;

@interface _TtC25PlaylistTuningFeatureImpl24PTAdditionalCallToAction : NSObject <SPTFreeTierPlaylistAdditionalCallToAction>
{
    // Error parsing type: , name: alertInterface
    // Error parsing type: , name: dataLoaderFactory
    // Error parsing type: , name: networkConnectivityController
    // Error parsing type: , name: saveEventLoopConnector
    // Error parsing type: , name: viewDependencies
    // Error parsing type: , name: lifecycleState
    // Error parsing type: , name: viewBinder
    // Error parsing type: , name: delegate
    // Error parsing type: , name: freeTierPlaylistViewController
    // Error parsing type: , name: eventConsumer
    // Error parsing type: , name: playlistModel
}

- (void).cxx_destruct;
- (id)init;
- (void)didRenderInView:(id)arg1;
- (void)performAction:(id)arg1;
- (void)didAppearInViewController:(id)arg1;
@property(nonatomic, readonly) _Bool enabled;
@property(nonatomic, readonly) _Bool selected;
@property(nonatomic, readonly) unsigned long long icon;
@property(nonatomic) __weak id <SPTFreeTierPlaylistAdditionalCallToActionDelegate> delegate; // @synthesize delegate;

@end

