//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@interface _TtC25PlaylistTuningFeatureImpl16PTCenteredSlider : UIControl
{
    // Error parsing type: , name: scopeBar
    // Error parsing type: , name: extentBar
    // Error parsing type: , name: extentThumb
    // Error parsing type: , name: initialDragX
    // Error parsing type: , name: releaseFeedback
    // Error parsing type: , name: snapFeedback
    // Error parsing type: , name: isContinuous
    // Error parsing type: , name: snapToCenter
    // Error parsing type: , name: value
}

- (void).cxx_destruct;
- (void)handlePan:(id)arg1;
- (void)layoutSubviews;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

