//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SettingsSection.h"

@interface _TtC24CarModeEngineFeatureImpl28CarModeEngineSettingsSection : SettingsSection
{
    // Error parsing type: , name: localSettings
    // Error parsing type: , name: $__lazy_storage_$_cell
}

- (void).cxx_destruct;
- (id)initWithSettingsViewController:(id)arg1;
- (void)didTapSwitchWithSender:(id)arg1;
- (id)footerText;
- (id)cellForRow:(long long)arg1;
@property(nonatomic, readonly) long long numberOfRows;

@end

