//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC23YourLibraryXFeatureImpl21YourLibraryHeaderView : UIView
{
    // Error parsing type: , name: theme
    // Error parsing type: , name: mainContentView
    // Error parsing type: , name: $__lazy_storage_$_titleLabel
    // Error parsing type: , name: $__lazy_storage_$_leadingButtonsStackView
    // Error parsing type: , name: $__lazy_storage_$_trailingButtonsStackView
    // Error parsing type: , name: $__lazy_storage_$_profileButton
    // Error parsing type: , name: $__lazy_storage_$_profilePlaceholderImage
    // Error parsing type: , name: $__lazy_storage_$_searchButton
    // Error parsing type: , name: $__lazy_storage_$_plusButton
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

