//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _TtC25PlaylistTuningFeatureImpl16PTViewController : UIViewController
{
    // Error parsing type: , name: playlistURI
    // Error parsing type: , name: formatListAttributes
    // Error parsing type: , name: loopController
    // Error parsing type: , name: glueTheme
    // Error parsing type: , name: dismissEventSource
    // Error parsing type: , name: saveEventSource
    // Error parsing type: , name: _view
    // Error parsing type: , name: $__lazy_storage_$_viewBinder
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)saveButtonTapped;
- (void)closeButtonTapped;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithCoder:(id)arg1;

@end

