//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC18WrappedFeatureImpl28LoadStoryAssetsEffectHandler : NSObject
{
    // Error parsing type: , name: dataLoader
    // Error parsing type: , name: cache
    // Error parsing type: , name: lock
    // Error parsing type: , name: queue
    // Error parsing type: , name: consumer
    // Error parsing type: , name: loadingStories
}

- (void).cxx_destruct;
- (id)init;

@end

