//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC26YourLibraryBetaFeatureImpl43YourLibraryBetaShareFeedbackTableViewBinder : NSObject
{
    // Error parsing type: , name: tableView
    // Error parsing type: , name: tableViewBottomConstraint
    // Error parsing type: , name: eventConsumer
    // Error parsing type: , name: style
    // Error parsing type: , name: lastModel
    // Error parsing type: , name: $__lazy_storage_$_placeholderTextView
    // Error parsing type: , name: $__lazy_storage_$_footerView
}

- (void).cxx_destruct;
- (id)init;
- (void)didTapSendButton;
- (void)dealloc;

@end

