//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC20SuperbirdFeatureImpl23VoiceAppProtocolHandler : NSObject
{
    // Error parsing type: , name: voiceSession
    // Error parsing type: , name: thingViewIntentsHandler
    // Error parsing type: , name: playbackController
    // Error parsing type: , name: audioRecorder
    // Error parsing type: , name: payloadConstructor
    // Error parsing type: , name: earconPlayer
    // Error parsing type: , name: ttsPlayer
    // Error parsing type: , name: voiceResponse
    // Error parsing type: , name: voiceSessionUpdates
    // Error parsing type: , name: voiceSessionId
    // Error parsing type: , name: shouldUnpause
}

- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

