//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@protocol _TtP20EncoreConsumerMobile18HeaderViewDelegate_;

@interface _TtC20EncoreConsumerMobile10HeaderView : UIView
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: backgroundView
    // Error parsing type: , name: foregroundView
    // Error parsing type: , name: contentView
    // Error parsing type: , name: topAccessoryView
    // Error parsing type: , name: clippingView
    // Error parsing type: , name: topAccessoryViewContainer
    // Error parsing type: , name: contentViewContainer
    // Error parsing type: , name: backgroundViewContainer
    // Error parsing type: , name: foregroundViewContainer
    // Error parsing type: , name: safeAreaView
    // Error parsing type: , name: headerContentContainer
    // Error parsing type: , name: totalHeaderLayoutGuide
    // Error parsing type: , name: contentContainerLayoutGuide
    // Error parsing type: , name: topAccessoryContainerLayoutGuide
    // Error parsing type: , name: totalHeaderLayoutGuideHeightConstraint
    // Error parsing type: , name: contentContainerLayoutGuideHeightConstraint
    // Error parsing type: , name: topAccessoryContainerLayoutGuideHeightConstraint
    // Error parsing type: , name: topAccessoryContainerTopConstraint
    // Error parsing type: , name: safeAreaViewTopConstraint
    // Error parsing type: , name: previousContentViewProgress
    // Error parsing type: , name: previousTopAccessoryViewProgress
    // Error parsing type: , name: previousBackgroundAndForegroundViewProgress
    // Error parsing type: , name: previousTotalHeaderViewProgress
    // Error parsing type: , name: contentViewHeight
    // Error parsing type: , name: topAccessoryViewHeight
    // Error parsing type: , name: topAccessoryViewVerticalOffset
    // Error parsing type: , name: isRemounting
    // Error parsing type: , name: adjustsToSafeAreaTopInset
}

- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (struct CGSize)systemLayoutSizeFittingSize:(struct CGSize)arg1;
- (void)forceLayoutAnimated:(_Bool)arg1;
- (void)safeAreaInsetsDidChange;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)didMoveToSuperview;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) double topAccessoryViewVerticalOffset; // @synthesize topAccessoryViewVerticalOffset;
@property(nonatomic, retain) id <_TtP20EncoreConsumerMobile18HeaderViewDelegate_> delegate; // @synthesize delegate;

@end

