//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC33EpisodeSegmentsFetcherFeatureImpl25EpisodeSegmentsEntityImpl.h"

@class NSString;

@interface _TtC33EpisodeSegmentsFetcherFeatureImpl25EpisodeSegmentsEntityImpl (EpisodeSegmentsFetcherFeatureImpl)
@property(nonatomic, readonly) _Bool isTalkSegment;
@property(nonatomic, readonly) _Bool isMusicSegment;
@property(nonatomic, readonly) NSString *trackSubtitle;
@end

