//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC27ListeningHistoryFeatureImpl27ListeningHistoryTableBinder : NSObject
{
    // Error parsing type: , name: tableView
    // Error parsing type: , name: theme
    // Error parsing type: , name: eventConsumer
    // Error parsing type: , name: trackRowFactory
    // Error parsing type: , name: listeningHistoryLogger
    // Error parsing type: , name: playingEntityURL
    // Error parsing type: , name: sections
}

- (void).cxx_destruct;
- (id)init;

@end

