//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC24PodcastChartsFeatureImpl24PodcastChartsRankRowView : UIView
{
    // Error parsing type: , name: rootStackView
    // Error parsing type: , name: rankStackView
    // Error parsing type: , name: labelStackView
    // Error parsing type: , name: podcastImageView
    // Error parsing type: , name: rankChangeImageView
    // Error parsing type: , name: rankLabel
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: subtitleLabel
}

- (void).cxx_destruct;
- (void)glue_applyStyle:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

