//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC26YourLibraryBetaFeatureImpl22YourLibraryBetaService : NSObject
{
    // Error parsing type: , name: containerService
    // Error parsing type: , name: clientSessionService
    // Error parsing type: , name: pageLoaderViewService
    // Error parsing type: , name: remoteConfigurationService
    // Error parsing type: , name: loopController
    // Error parsing type: , name: glueService
    // Error parsing type: , name: uiPresentationService
    // Error parsing type: , name: pageToken
    // Error parsing type: , name: testManager
    // Error parsing type: , name: $__lazy_storage_$_experienceRegistry
    // Error parsing type: , name: $__lazy_storage_$_feedbackTheme
}

+ (id)serviceIdentifier;
- (void).cxx_destruct;
- (id)init;
- (id)provideFeedbackFactory;
- (id)provideExperienceRegistry;
- (id)provideTestManager;
- (id)provideViewControllerWithUri:(id)arg1 pageCreationContext:(id)arg2;
- (void)load;
- (void)configureWithServices:(id)arg1;

@end

