//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC21OfflineMixFeatureImpl11TestManager : NSObject
{
    // Error parsing type: , name: userCuratedOfflineMixEnabled
    // Error parsing type: , name: spotifyCuratedOfflineMixEnabled
}

- (id)init;
@property(nonatomic, readonly) _Bool spotifyCuratedOfflineMixEnabled; // @synthesize spotifyCuratedOfflineMixEnabled;
@property(nonatomic, readonly) _Bool userCuratedOfflineMixEnabled; // @synthesize userCuratedOfflineMixEnabled;

@end

