//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC23MusicVideoUIFeatureImplP33_225C01830BF4956BA7BC726601459EC814PlayerObserver : NSObject
{
    // Error parsing type: , name: player
    // Error parsing type: , name: delegate
}

- (void).cxx_destruct;
- (id)init;
- (void)player:(id)arg1 stateDidChange:(id)arg2 fromState:(id)arg3;
- (void)dealloc;

@end

