//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC18VoiceUIFeatureImpl31OnboardingViewControllerFactory : _TtCs12_SwiftObject
{
    // Error parsing type: , name: $__lazy_storage_$_mobiusController
    // Error parsing type: , name: $__lazy_storage_$_onboardingMode
    // Error parsing type: , name: microphonePermissions
    // Error parsing type: , name: testManager
    // Error parsing type: , name: dismissHandler
}

@end

