//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class _TtC20SingalongFeatureImpl11TestManager;

@interface _TtC20SingalongFeatureImpl16SingalongService : NSObject
{
    // Error parsing type: , name: containerService
    // Error parsing type: , name: remoteConfigurationService
    // Error parsing type: , name: testManager
}

+ (id)serviceIdentifier;
- (void).cxx_destruct;
- (id)init;
- (void)load;
- (void)configureWithServices:(id)arg1;
@property(nonatomic, retain) _TtC20SingalongFeatureImpl11TestManager *testManager; // @synthesize testManager;

@end

