//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC18WrappedFeatureImpl30DecadeMinutesListenedStoryView : UIView
{
    // Error parsing type: , name: captionLabel
    // Error parsing type: , name: recordView
    // Error parsing type: , name: minuteStackView
    // Error parsing type: , name: yearStackView
    // Error parsing type: , name: recordContainerView
    // Error parsing type: , name: minuteStackViewTopConstraint
    // Error parsing type: , name: minuteStackViewHeightConstraint
    // Error parsing type: , name: yearStackViewTopConstraint
    // Error parsing type: , name: yearStackViewHeightConstraint
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

