//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC18WrappedFeatureImpl15SeasonStoryView : UIView
{
    // Error parsing type: , name: captionLabel
    // Error parsing type: , name: seasonLabel
    // Error parsing type: , name: tile1
    // Error parsing type: , name: tile2
    // Error parsing type: , name: tile3
    // Error parsing type: , name: tile4
    // Error parsing type: , name: contentView
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

