//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCV35PodcastCreatorEntityPageFeatureImpl20PodcastCreatorEntityP33_6D31915CE84282750D830245EEA9684113_StorageClass : _TtCs12_SwiftObject
{
    // Error parsing type: , name: _uri
    // Error parsing type: , name: _displayName
    // Error parsing type: , name: _logo
    // Error parsing type: , name: _coverImage
    // Error parsing type: , name: _description_p
    // Error parsing type: , name: _tags
    // Error parsing type: , name: _pinnedEntities
    // Error parsing type: , name: _episodes
    // Error parsing type: , name: _appearsOn
    // Error parsing type: , name: _shows
    // Error parsing type: , name: _linkedCreators
    // Error parsing type: , name: _recommended
    // Error parsing type: , name: _tours
    // Error parsing type: , name: _offers
    // Error parsing type: , name: _bio
    // Error parsing type: , name: _gallery
    // Error parsing type: , name: _instagram
    // Error parsing type: , name: _facebook
    // Error parsing type: , name: _twitter
}

@end

