//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC25PlaylistTuningFeatureImpl21PlaylistTuningService : NSObject
{
    // Error parsing type: , name: audioPreviewService
    // Error parsing type: , name: containerService
    // Error parsing type: , name: contextMenuService
    // Error parsing type: , name: freeTierPlaylistUIService
    // Error parsing type: , name: glueService
    // Error parsing type: , name: networkService
    // Error parsing type: , name: playlistPlatformService
    // Error parsing type: , name: remoteConfigurationService
    // Error parsing type: , name: additionalCTAToken
    // Error parsing type: , name: onboardingMobiusController
}

+ (id)serviceIdentifier;
- (void).cxx_destruct;
- (id)init;
- (void)unload;
- (void)load;
- (void)configureWithServices:(id)arg1;

@end

