//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "HUGSThemableComponentView.h"

@interface _TtC24PodcastChartsFeatureImpl33PodcastChartsRankRowComponentView : HUGSThemableComponentView
{
    // Error parsing type: , name: imageLoader
    // Error parsing type: , name: rowIndexCustomDataKey
    // Error parsing type: , name: rankIconCustomDataKey
    // Error parsing type: , name: rankIconUp
    // Error parsing type: , name: rankIconDown
    // Error parsing type: , name: rankIconNew
    // Error parsing type: , name: rankIconUnchanged
    // Error parsing type: , name: rowView
    // Error parsing type: , name: rankIconUpImage
    // Error parsing type: , name: rankIconDownImage
    // Error parsing type: , name: rankIconNewImage
}

- (void).cxx_destruct;
- (id)initWithTheme:(id)arg1 frame:(struct CGRect)arg2;
- (void)applyThemeLayout;
- (void)configureWithModel:(id)arg1;

@end

