//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPTUIPageService.h"

@interface _TtC22HubSwiftExampleFeature22HubSwiftExampleService : SPTUIPageService
{
    // Error parsing type: , name: hubSwiftService
}

+ (id)serviceIdentifier;
- (void).cxx_destruct;
- (id)init;
- (id)provideViewControllerForURI:(id)arg1 context:(id)arg2;
- (_Bool)claimsURI:(id)arg1;
- (void)configureWithServices:(id)arg1;

@end

