//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC21OfflineMixFeatureImpl17OfflineMixService : NSObject
{
    // Error parsing type: , name: containerService
    // Error parsing type: , name: contextMenuService
    // Error parsing type: , name: containerUIService
    // Error parsing type: , name: freeTierPlaylistUIService
    // Error parsing type: , name: networkService
    // Error parsing type: , name: playlistPlatformService
    // Error parsing type: , name: remoteConfigurationService
    // Error parsing type: , name: sessionService
    // Error parsing type: , name: $__lazy_storage_$_offlineMixServiceClient
    // Error parsing type: , name: $__lazy_storage_$_offlineMixPlaylistDataLoader
    // Error parsing type: , name: $__lazy_storage_$_dialogPresenter
    // Error parsing type: , name: $__lazy_storage_$_downloadManager
    // Error parsing type: , name: $__lazy_storage_$_modelProvider
    // Error parsing type: , name: $__lazy_storage_$_playlistFilter
    // Error parsing type: , name: $__lazy_storage_$_isLimitedOfflineEnabled
    // Error parsing type: , name: testManager
    // Error parsing type: , name: token
}

+ (id)serviceIdentifier;
- (void).cxx_destruct;
- (id)init;
- (id)provideTestManager;
- (id)providePlaylistFilter;
- (id)provideModelProvider;
- (id)provideDownloadManager;
- (id)provideDataLoader;
- (void)unload;
- (void)load;
- (void)configureWithServices:(id)arg1;

@end

