//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC18WrappedFeatureImpl5Story.h"

@interface _TtC18WrappedFeatureImpl11SeasonStory : _TtC18WrappedFeatureImpl5Story
{
    // Error parsing type: , name: template
    // Error parsing type: , name: caption
    // Error parsing type: , name: title
    // Error parsing type: , name: image1URL
    // Error parsing type: , name: image2URL
    // Error parsing type: , name: image3URL
    // Error parsing type: , name: image4URL
}

@end

