//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC22QuickScrollFeatureImpl15QuickScrollView.h"

@interface _TtC22QuickScrollFeatureImpl15QuickScrollView (QuickScrollFeatureImpl1)
- (void)reset;
- (void)attachScrollView:(id)arg1;
@property(nonatomic) _Bool isActive;
@end

