//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC28NowPlayingEpisodeFeatureImpl37NowPlayingEpisodeContentLayerProvider : NSObject
{
    // Error parsing type: , name: isMixedMediaEpisodeEnabled
    // Error parsing type: , name: episodePlayer
    // Error parsing type: , name: imageLoader
}

- (void).cxx_destruct;
- (id)init;

@end

