//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC29PlaylistAnnotationFeatureImpl25PlaylistAnnotationService : NSObject
{
    // Error parsing type: , name: containerUIService
    // Error parsing type: , name: uiPresentationService
    // Error parsing type: , name: playlistPlatformService
}

+ (id)serviceIdentifier;
- (void).cxx_destruct;
- (id)init;
- (id)providePlaylistAnnotationViewControllerWithPlaylistURI:(id)arg1 name:(id)arg2 description:(id)arg3;
- (void)unload;
- (void)load;
- (void)configureWithServices:(id)arg1;

@end

