//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC23CarDetectionFeatureImpl19CarDetectionService : NSObject
{
    // Error parsing type: , name: containerService
    // Error parsing type: , name: accessoryManagerService
    // Error parsing type: , name: carmageddonService
    // Error parsing type: , name: featureFlaggingService
    // Error parsing type: , name: loop
    // Error parsing type: , name: carDetector
    // Error parsing type: , name: legacyController
    // Error parsing type: , name: testManager
}

+ (id)serviceIdentifier;
- (void).cxx_destruct;
- (id)init;
- (id)provideLegacyController;
- (id)provideCarDetector;
- (void)unload;
- (void)load;
- (void)configureWithServices:(id)arg1;

@end

