//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC22ConnectUIV2FeatureImpl45DevicePickerSectionHeaderShadowBackgroundView : UIView
{
    // Error parsing type: , name: maskColor
    // Error parsing type: , name: $__lazy_storage_$_maskLayerContainer
    // Error parsing type: , name: $__lazy_storage_$_contentMaskLayer
    // Error parsing type: , name: $__lazy_storage_$_bottomMaskLayer
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;

@end

