//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC27ListeningHistoryFeatureImpl27ListeningHistoryTableBinder.h"

@interface _TtC27ListeningHistoryFeatureImpl27ListeningHistoryTableBinder (ListeningHistoryFeatureImpl2)
- (void)unhideWithSender:(id)arg1;
- (void)unbanWithSender:(id)arg1;
- (void)unlikeWithSender:(id)arg1;
- (void)contextMenuTappedWithSender:(id)arg1;
- (void)tappedWithSender:(id)arg1;
@end

