//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC22AllBoardingFeatureImpl18AllBoardingService : NSObject
{
    // Error parsing type: , name: containerService
    // Error parsing type: , name: settingsService
    // Error parsing type: , name: uriDispatchService
    // Error parsing type: , name: uiPresentationService
    // Error parsing type: , name: networkService
    // Error parsing type: , name: pageLoaderViewService
    // Error parsing type: , name: glueService
    // Error parsing type: , name: clientSessionService
    // Error parsing type: , name: ubiService
    // Error parsing type: , name: followFeature
    // Error parsing type: , name: instrumentationService
    // Error parsing type: , name: featureFlaggingService
    // Error parsing type: , name: eventSenderService
    // Error parsing type: , name: tasteOnboardingDeeplinkService
    // Error parsing type: , name: remoteConfigurationService
    // Error parsing type: , name: loginOnboardingService
    // Error parsing type: , name: debugFeatureManager
    // Error parsing type: , name: $__lazy_storage_$_flowCoordinator
    // Error parsing type: , name: $__lazy_storage_$_curationManager
    // Error parsing type: , name: $__lazy_storage_$_remoteConfigurationProperties
}

+ (id)serviceIdentifier;
- (void).cxx_destruct;
- (id)init;
- (void)applicationDidBecomeActive;
- (void)unload;
- (void)load;
- (void)configureWithServices:(id)arg1;

@end

