//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC25PlaylistTuningFeatureImpl17PTTableViewBinder : NSObject
{
    // Error parsing type: , name: tableView
    // Error parsing type: , name: audioPreviewModelFactory
    // Error parsing type: , name: audioPreviewUIFactory
    // Error parsing type: , name: contextMenuOptions
    // Error parsing type: , name: contextMenuPresenterFactory
    // Error parsing type: , name: explicitContentAccessManager
    // Error parsing type: , name: glueTheme
    // Error parsing type: , name: imageLoader
    // Error parsing type: , name: logger
    // Error parsing type: , name: trackRowConfiguration
    // Error parsing type: , name: currentTracks
}

- (void).cxx_destruct;
- (id)init;
- (void)audioPreviewTappedWithButton:(id)arg1;
- (void)contextMenuTappedWithButton:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;

@end

