//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC18WrappedFeatureImpl11StoriesView : UIView
{
    // Error parsing type: , name: storyContainerView
    // Error parsing type: , name: actionContainerView
    // Error parsing type: , name: storyContentView
    // Error parsing type: , name: segmentedProgressView
    // Error parsing type: , name: volumeButton
    // Error parsing type: , name: closeButton
    // Error parsing type: , name: shareStoryButton
    // Error parsing type: , name: storyHeaderGradientView
    // Error parsing type: , name: storyHeaderImageView
    // Error parsing type: , name: actionContainerGradientView
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

