//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC23ConnectivityFeatureImpl40ClientTokenPersistentUserDefaultsStorage : _TtCs12_SwiftObject
{
    // Error parsing type: , name: userDefaults
}

- (_Bool)getPSESFlag;
- (void)storePSESFlag:(_Bool)arg1;
- (void)clearClientToken;
- (id)getEncryptedClientToken;
- (void)storeEncryptedClientToken:(id)arg1;

@end

