//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC28NowPlayingEpisodeFeatureImpl23NowPlayingEpisodePlayer : NSObject
{
    // Error parsing type: , name: dataLoader
    // Error parsing type: , name: observers
    // Error parsing type: , name: model
    // Error parsing type: , name: player
    // Error parsing type: , name: currentState
    // Error parsing type: , name: timer
    // Error parsing type: , name: densityFactor
}

- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

