//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC28EncoreIntegrationFeatureImpl18ComponentFactories.h"

@interface _TtC28EncoreIntegrationFeatureImpl18ComponentFactories (EncoreIntegrationFeatureImpl6)
- (id)makeTrackRowChart:(long long)arg1;
- (id)makeTrackRowChart;
@end

