//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "HUGSThemableComponentView.h"

@protocol HUBComponentEventHandler;

@interface _TtC35PodcastCreatorEntityPageFeatureImpl30PopularEpisodeHubComponentView : HUGSThemableComponentView
{
    // Error parsing type: , name: eventHandler
    // Error parsing type: , name: $__lazy_storage_$_indexLabel
    // Error parsing type: , name: imageView
    // Error parsing type: , name: $__lazy_storage_$_rowView
    // Error parsing type: , name: $__lazy_storage_$_control
    // Error parsing type: , name: imageSize
}

- (void).cxx_destruct;
- (id)initWithTheme:(id)arg1 frame:(struct CGRect)arg2;
@property(nonatomic, retain) id <HUBComponentEventHandler> eventHandler; // @synthesize eventHandler;

@end

