//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCC21PodcastDALFeatureImpl31PodcastDataLoaderImplementationP33_A40CEA865253BDE4A232004B8057A7DC34DataLoaderDispatcherImplementation : _TtCs12_SwiftObject
{
}

@end

