//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "HUBViewController.h"

@class NSURL;

@interface _TtC35PodcastCreatorEntityPageFeatureImpl31CreatorEntityPageViewController : HUBViewController
{
    // Error parsing type: , name: pageURI
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: theme
}

- (void).cxx_destruct;
- (id)initWithComponentRegistry:(id)arg1 componentLayoutManager:(id)arg2 imageLoaderFactory:(id)arg3 commandHandler:(id)arg4;
- (void)viewDidLoad;
- (id)spt_pageURI;

// Remaining properties
@property(nonatomic, readonly) NSURL *pageURI;

@end

