//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC19HubSwiftFeatureImpl29HubSwiftServiceImplementation : NSObject
{
    // Error parsing type: , name: containerService
    // Error parsing type: , name: hubsService
    // Error parsing type: , name: glueService
    // Error parsing type: , name: pageLoaderViewService
    // Error parsing type: , name: performanceMetricsService
    // Error parsing type: , name: $__lazy_storage_$_hubsRendererFactory
    // Error parsing type: , name: $__lazy_storage_$_hugsFactory
    // Error parsing type: , name: $__lazy_storage_$_theme
}

+ (id)serviceIdentifier;
- (void).cxx_destruct;
- (id)init;
- (void)unload;
- (void)load;
- (void)configureWithServices:(id)arg1;

@end

