//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIView;

@interface _TtCO20EncoreConsumerMobile5Views10HeaderView : NSObject
{
    // Error parsing type: , name: uiView
    // Error parsing type: , name: onProgress
    // Error parsing type: , name: onFullHeaderProgress
    // Error parsing type: , name: onRemount
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, retain) UIView *uiView; // @synthesize uiView;

@end

