//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC18WrappedFeatureImpl16SummaryStoryView : UIView
{
    // Error parsing type: , name: captionLabel
    // Error parsing type: , name: imageViews
    // Error parsing type: , name: cardsStackView
    // Error parsing type: , name: cardsScrollView
    // Error parsing type: , name: cardsPageControl
    // Error parsing type: , name: shareButton
    // Error parsing type: , name: cardCount
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

