//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC18WrappedFeatureImpl16StackedImageView : UIView
{
    // Error parsing type: , name: imageViews
    // Error parsing type: , name: imageViewLeadingAnchorConstraints
    // Error parsing type: , name: imageViewTopAnchorConstraints
    // Error parsing type: , name: imageViewWidthAnchorConstraints
    // Error parsing type: , name: image
    // Error parsing type: , name: origin
    // Error parsing type: , name: scaleFactor
    // Error parsing type: , name: stackCount
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(nonatomic) long long contentMode;
@property(nonatomic) _Bool clipsToBounds;

@end

