//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC18WrappedFeatureImpl22GlobalCitizenStoryView : UIView
{
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: captionLabel
    // Error parsing type: , name: paragraph1Label
    // Error parsing type: , name: globeView
    // Error parsing type: , name: artistNameLabel
    // Error parsing type: , name: countryLabel
    // Error parsing type: , name: artistImageView
    // Error parsing type: , name: imageViews
    // Error parsing type: , name: artistCount
    // Error parsing type: , name: globeNode
    // Error parsing type: , name: globeScene
    // Error parsing type: , name: globeSceneView
    // Error parsing type: , name: globeStrokeView
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

