//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "HUGSThemableComponentView.h"

@interface _TtC24PodcastChartsFeatureImpl32PodcastChartsHeaderComponentView : HUGSThemableComponentView
{
    // Error parsing type: , name: $__lazy_storage_$_headerView
}

- (void).cxx_destruct;
- (void)applyThemeLayout;
- (void)configureWithModel:(id)arg1;
- (id)initWithTheme:(id)arg1 frame:(struct CGRect)arg2;

@end

