//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC20SuperbirdFeatureImpl16SuperbirdService : NSObject
{
    // Error parsing type: , name: remoteConfigurationService
    // Error parsing type: , name: appProtocolService
    // Error parsing type: , name: networkService
    // Error parsing type: , name: voiceLibraryService
    // Error parsing type: , name: playbackService
    // Error parsing type: , name: collectionPlatformService
    // Error parsing type: , name: playlistPlatformService
    // Error parsing type: , name: followService
    // Error parsing type: , name: gaiaService
    // Error parsing type: , name: appProtocolExternalHandler
    // Error parsing type: , name: configurationProperties
}

+ (id)serviceIdentifier;
- (void).cxx_destruct;
- (id)init;
- (void)unload;
- (void)load;
- (void)configureWithServices:(id)arg1;

@end

