//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC23YourLibraryXFeatureImpl19YourLibraryXService : NSObject
{
    // Error parsing type: , name: clientSessionService
    // Error parsing type: , name: containerService
    // Error parsing type: , name: collectionPlatformService
    // Error parsing type: , name: filterChipsService
    // Error parsing type: , name: remoteConfigurationService
    // Error parsing type: , name: pageLoaderViewService
    // Error parsing type: , name: profileService
    // Error parsing type: , name: dispatchService
    // Error parsing type: , name: glueService
    // Error parsing type: , name: playlistPlatformService
    // Error parsing type: , name: yourlibraryXDataService
    // Error parsing type: , name: ubiService
    // Error parsing type: , name: sortingFilteringService
    // Error parsing type: , name: uiPresentationService
    // Error parsing type: , name: yourLibraryXPageToken
    // Error parsing type: , name: testManager
    // Error parsing type: , name: contentFilterItemLoader
    // Error parsing type: , name: $__lazy_storage_$_localSettings
    // Error parsing type: , name: $__lazy_storage_$_instrumentation
}

+ (id)serviceIdentifier;
- (void).cxx_destruct;
- (id)init;
- (id)provideYourLibraryViewController;
- (void)unload;
- (void)load;
- (void)configureWithServices:(id)arg1;
- (id)provideAssistantBannerViewFactory;
- (id)provideTestManager;

@end

