//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPTService-Protocol.h"

@class SPTApplicationStateTracker, SPTAudioVolumeControl, SPTIncognitoModeHandler, SPTLogger, SPTPlayerMftCanPlayChecker, SPTPlayerProxyContextPlayer, SPTSocialManager, SPTUserFactory;
@protocol SPTEntityService, SPTOfflineManager, SPTResolver;

@protocol _TtP18CoreSessionFeature21SPTCoreSessionService_ <SPTService>
- (SPTIncognitoModeHandler *)provideIncognitoModeHandler;
- (id <SPTOfflineManager>)provideOfflineManager;
- (SPTUserFactory *)provideUserFactory;
- (SPTSocialManager *)provideSocialManager;
- (SPTPlayerProxyContextPlayer *)provideProxyContextPlayer;
- (SPTPlayerMftCanPlayChecker *)provideMFTCanPlayChecker;
- (SPTAudioVolumeControl *)provideAudioVolumeControl;
- (id <SPTEntityService>)provideEntityService;
- (SPTLogger *)provideLogger;
- (SPTApplicationStateTracker *)provideApplicationStateTracker;
- (id <SPTResolver>)provideCosmosRouter;
@end

