//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, NSURL;
@protocol _TtP16ProfileV2Feature32SPTProfileUserDataChangeObserver_;

@protocol _TtP16ProfileV2Feature18SPTProfileUserData_
- (void)removeProfileChangeObserverWithObserver:(id <_TtP16ProfileV2Feature32SPTProfileUserDataChangeObserver_>)arg1;
- (void)addProfileChangeObserverWithObserver:(id <_TtP16ProfileV2Feature32SPTProfileUserDataChangeObserver_>)arg1;
@property(nonatomic, readonly) _Bool isVerified;
@property(nonatomic, readonly) NSURL *imageURL;
@property(nonatomic, readonly) NSString *displayName;
@property(nonatomic, readonly) NSString *username;
@end

