//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSURL;
@protocol HUBCommandHandler, SPTFreeTierEntityOfflineViewModel;

@protocol _TtP17OfflineMixFeature26SPTOfflineMixModelProvider_
- (id <HUBCommandHandler>)provideFreeTierTrackOfflineToggleCommandHandlerFor:(id <SPTFreeTierEntityOfflineViewModel>)arg1;
- (id <SPTFreeTierEntityOfflineViewModel>)provideFreeTierTrackOfflineButtonViewModelFor:(NSURL *)arg1;
@end

