//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPTService-Protocol.h"

@class NSArray;
@protocol SPTPodcastDataLoader, SPTPodcastEpisodeFactory, SPTPodcastFactory, SPTPodcastRequest, SPTPodcastRequestData, SPTResolver;

@protocol _TtP17PodcastDALFeature20SPTPodcastDALService_ <SPTService>
- (id <SPTPodcastDataLoader>)provideDataLoaderWithResolver:(id <SPTResolver>)arg1;
- (id <SPTPodcastRequestData>)provideUpdateEpisodeUnplayedRequestDataWithURIStrings:(NSArray *)arg1 markAsUnplayed:(_Bool)arg2;
- (id <SPTPodcastRequest>)providePodcastRequestWithData:(id <SPTPodcastRequestData>)arg1;
- (id <SPTPodcastEpisodeFactory>)providePodcastEpisodeFactory;
- (id <SPTPodcastFactory>)providePodcastFactory;
@end

