//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class UIViewController, _TtC23SharePreviewMenuFeature29SharePreviewMenuConfiguration;
@protocol _TtP23SharePreviewMenuFeature36SharePreviewMenuPresentationDelegate_;

@protocol _TtP23SharePreviewMenuFeature23SharePreviewMenuFactory_
- (UIViewController *)makeMenuWith:(_TtC23SharePreviewMenuFeature29SharePreviewMenuConfiguration *)arg1 presentationDelegate:(id <_TtP23SharePreviewMenuFeature36SharePreviewMenuPresentationDelegate_>)arg2;
@end

