//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSURL;
@protocol SPTPageCreationContext, _TtP30PodcastEpisodeAudioPlusFeature37PodcastEpisodeAudioPlusViewController_;

@protocol _TtP30PodcastEpisodeAudioPlusFeature38SPTPodcastEpisodeAudioPlusViewProvider_
- (id <_TtP30PodcastEpisodeAudioPlusFeature37PodcastEpisodeAudioPlusViewController_>)audioPlusForEpisodeURIWithUri:(NSURL *)arg1 context:(id <SPTPageCreationContext>)arg2;
@end

