//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol GLUEStatefulItem <NSObject>
@property(nonatomic) _Bool active;
- (_Bool)isActive;
@property(nonatomic) _Bool selected;
- (_Bool)isSelected;
@property(nonatomic) _Bool disabled;
- (_Bool)isDisabled;
@property(nonatomic) _Bool highlighted;
- (_Bool)isHighlighted;
@property(nonatomic, readonly) unsigned long long state;
@end

