//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class EventEnvelope, NSArray, NSString;

@protocol INSSchedulerDataDelegate <NSObject>
- (void)didFailEnvelopes:(NSArray *)arg1;
- (void)didDeliverEnvelopes:(NSArray *)arg1;
- (void)scheduleNonAuthenticatedEnvelope:(EventEnvelope *)arg1;
- (void)scheduleAuthenticatedEnvelope:(EventEnvelope *)arg1 withOwner:(NSString *)arg2;
@end

