//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface INTERNAL_SPTEncoreTrackRowChartModel : NSObject
{
    // Error parsing type: , name: name
    // Error parsing type: , name: artists
    // Error parsing type: , name: addedBy
    // Error parsing type: , name: coverArt
    // Error parsing type: , name: rowNumber
    // Error parsing type: , name: indicatorState
    // Error parsing type: , name: downloadState
    // Error parsing type: , name: restriction
    // Error parsing type: , name: isPremiumOnly
    // Error parsing type: , name: isPlaying
    // Error parsing type: , name: isPlayable
    // Error parsing type: , name: modifier
    // Error parsing type: , name: isPressed
    // Error parsing type: , name: deviceOffline
}

- (void).cxx_destruct;
- (id)init;
- (_Bool)isEqual:(id)arg1;
- (id)initWithName:(id)arg1 artists:(id)arg2 addedBy:(id)arg3 coverArt:(id)arg4 rowNumber:(long long)arg5 indicatorState:(long long)arg6 downloadState:(long long)arg7 restriction:(long long)arg8 isPremiumOnly:(_Bool)arg9 isPlaying:(_Bool)arg10 isPlayable:(_Bool)arg11 modifier:(long long)arg12 isPressed:(_Bool)arg13 deviceOffline:(_Bool)arg14;

@end

