//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface INTERNAL_SPTEncoreSectionHeadingModel : NSObject
{
    // Error parsing type: , name: title
    // Error parsing type: , name: subtitle
    // Error parsing type: , name: style
}

- (void).cxx_destruct;
- (id)init;
- (_Bool)isEqual:(id)arg1;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 style:(long long)arg3;
@property(nonatomic, readonly) long long style; // @synthesize style;
@property(nonatomic, readonly) NSString *subtitle;
@property(nonatomic, readonly) NSString *title;

@end

