//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface INTERNAL_SPTEncoreTrackRowArtistModel : NSObject
{
    // Error parsing type: , name: name
    // Error parsing type: , name: numberOfListeners
    // Error parsing type: , name: rowNumber
    // Error parsing type: , name: coverArt
    // Error parsing type: , name: downloadState
    // Error parsing type: , name: restriction
    // Error parsing type: , name: isPremiumOnly
    // Error parsing type: , name: isPlaying
    // Error parsing type: , name: isPlayable
    // Error parsing type: , name: modifier
    // Error parsing type: , name: isPressed
}

- (void).cxx_destruct;
- (id)init;
- (_Bool)isEqual:(id)arg1;
- (id)initWithName:(id)arg1 numberOfListeners:(id)arg2 rowNumber:(long long)arg3 coverArt:(id)arg4 downloadState:(long long)arg5 restriction:(long long)arg6 isPremiumOnly:(_Bool)arg7 isPlaying:(_Bool)arg8 isPlayable:(_Bool)arg9 modifier:(long long)arg10 isPressed:(_Bool)arg11;
@property(nonatomic, readonly) _Bool isPressed; // @synthesize isPressed;
@property(nonatomic, readonly) long long modifier; // @synthesize modifier;
@property(nonatomic, readonly) _Bool isPlayable; // @synthesize isPlayable;
@property(nonatomic, readonly) _Bool isPlaying; // @synthesize isPlaying;
@property(nonatomic, readonly) _Bool isPremiumOnly; // @synthesize isPremiumOnly;
@property(nonatomic, readonly) long long restriction; // @synthesize restriction;
@property(nonatomic, readonly) long long downloadState; // @synthesize downloadState;
@property(nonatomic, readonly) NSURL *coverArt;
@property(nonatomic, readonly) long long rowNumber; // @synthesize rowNumber;
@property(nonatomic, readonly) NSString *numberOfListeners;
@property(nonatomic, readonly) NSString *name;

@end

