//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface INTERNAL_SPTEncorePlaylistHeaderModel : NSObject
{
    // Error parsing type: , name: name
    // Error parsing type: , name: creatorText
    // Error parsing type: , name: creatorImage
    // Error parsing type: , name: isBySpotify
    // Error parsing type: , name: playlistDescription
    // Error parsing type: , name: coverArtImage
    // Error parsing type: , name: coverArtColor
    // Error parsing type: , name: likes
    // Error parsing type: , name: duration
    // Error parsing type: , name: downloadState
    // Error parsing type: , name: isPlaying
    // Error parsing type: , name: isPlayable
    // Error parsing type: , name: isDownloadable
    // Error parsing type: , name: isLiked
    // Error parsing type: , name: minimumHeight
    // Error parsing type: , name: fullHeight
}

- (void).cxx_destruct;
- (id)init;
- (_Bool)isEqual:(id)arg1;
- (id)initWithName:(id)arg1 creatorText:(id)arg2 creatorImage:(id)arg3 isBySpotify:(_Bool)arg4 playlistDescription:(id)arg5 coverArtImage:(id)arg6 coverArtColor:(id)arg7 likes:(long long)arg8 duration:(double)arg9 downloadState:(long long)arg10 isPlaying:(_Bool)arg11 isPlayable:(_Bool)arg12 isDownloadable:(_Bool)arg13 isLiked:(_Bool)arg14 minimumHeight:(double)arg15 fullHeight:(double)arg16;

@end

