//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIColor, UIImage;

@interface INTERNAL_SPTEncoreArtistHeaderModel : NSObject
{
    // Error parsing type: , name: name
    // Error parsing type: , name: monthlyListeners
    // Error parsing type: , name: coverArtImage
    // Error parsing type: , name: coverArtColor
    // Error parsing type: , name: isPlaying
    // Error parsing type: , name: isPlayable
    // Error parsing type: , name: isFollowed
    // Error parsing type: , name: minimumHeight
    // Error parsing type: , name: fullHeight
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithName:(id)arg1 monthlyListeners:(id)arg2 coverArtImage:(id)arg3 coverArtColor:(id)arg4 isPlaying:(_Bool)arg5 isPlayable:(_Bool)arg6 isFollowed:(_Bool)arg7 minimumHeight:(double)arg8 fullHeight:(double)arg9;
@property(nonatomic, readonly) double fullHeight; // @synthesize fullHeight;
@property(nonatomic, readonly) double minimumHeight; // @synthesize minimumHeight;
@property(nonatomic, readonly) _Bool isFollowed; // @synthesize isFollowed;
@property(nonatomic, readonly) _Bool isPlayable; // @synthesize isPlayable;
@property(nonatomic, readonly) _Bool isPlaying; // @synthesize isPlaying;
@property(nonatomic, readonly) UIColor *coverArtColor; // @synthesize coverArtColor;
@property(nonatomic, readonly) UIImage *coverArtImage; // @synthesize coverArtImage;
@property(nonatomic, readonly) NSString *monthlyListeners;
@property(nonatomic, readonly) NSString *name;

@end

