//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SPTRemoteConfigurationContext;

@interface RCCURLCreator : NSObject
{
    id <SPTRemoteConfigurationContext> _context;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <SPTRemoteConfigurationContext> context; // @synthesize context=_context;
- (id)resolverURLWithFetchType:(id)arg1;
- (id)initWithRemoteConfigurationContext:(id)arg1;

@end

