//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIApplication.h>

@class NSHashTable;
@protocol SpotifyApplicationRemoteControlDelegate;

@interface SpotifyApplication : UIApplication
{
    id <SpotifyApplicationRemoteControlDelegate> _remoteControlDelegate;
    NSHashTable *_observers;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(nonatomic) __weak id <SpotifyApplicationRemoteControlDelegate> remoteControlDelegate; // @synthesize remoteControlDelegate=_remoteControlDelegate;
- (_Bool)canBecomeFirstResponder;
- (void)removeRemoteControlObserver:(id)arg1;
- (void)addRemoteControlObserver:(id)arg1;
- (_Bool)handleRemoteControlEventOfSubtype:(long long)arg1;
- (void)remoteControlReceivedWithEvent:(id)arg1;

@end

