//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SPTAuthSerializableCredentials;

@interface SPTAuthWebgateSession : NSObject
{
    unique_ptr_31f72f11 _authSession;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *username;
@property(readonly, nonatomic) SPTAuthSerializableCredentials *reusableCredentials;
@property(readonly, nonatomic) shared_ptr_e0806d77 oauthClient;
- (id)initWithSession:(unique_ptr_31f72f11)arg1;

@end

