//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SPTAdVoiceEvent : NSObject
{
}

- (_Bool)isEqual:(id)arg1;
- (id)mapFromTimerElapsed:(CDUnknownBlockType)arg1 speechSessionStarted:(CDUnknownBlockType)arg2 listeningPeriodStarted:(CDUnknownBlockType)arg3 speechResponseReceived:(CDUnknownBlockType)arg4 speechIntentRecognized:(CDUnknownBlockType)arg5 speechRecognitionError:(CDUnknownBlockType)arg6 adSlotsCleared:(CDUnknownBlockType)arg7 ctaClicked:(CDUnknownBlockType)arg8 playbackPaused:(CDUnknownBlockType)arg9 playbackBuffering:(CDUnknownBlockType)arg10 playbackResumed:(CDUnknownBlockType)arg11 cuePlayed:(CDUnknownBlockType)arg12 init:(CDUnknownBlockType)arg13 tearDown:(CDUnknownBlockType)arg14;

@end

