//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SPTAdsBaseCosmosBridge, SPTVoiceLibrarySession;

@interface SPTAdVoiceCosmosEffectHandler : NSObject
{
    id <SPTAdsBaseCosmosBridge> _cosmosBridge;
    id <SPTVoiceLibrarySession> _voiceSession;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <SPTVoiceLibrarySession> voiceSession; // @synthesize voiceSession=_voiceSession;
@property(readonly, nonatomic) id <SPTAdsBaseCosmosBridge> cosmosBridge; // @synthesize cosmosBridge=_cosmosBridge;
- (void)handleListenForAudioSignalEffect:(id)arg1 eventSink:(CDUnknownBlockType)arg2;
- (void)handleClearAdSlotsEffect:(id)arg1 eventSink:(CDUnknownBlockType)arg2;
- (void)handlePostMicOnEffect:(id)arg1 eventSink:(CDUnknownBlockType)arg2;
- (void)handlePostSpeechErrorEffect:(id)arg1 eventSink:(CDUnknownBlockType)arg2;
- (void)handlePostSpeechReceivedEffect:(id)arg1 eventSink:(CDUnknownBlockType)arg2;
- (id)initWithCosmosBridge:(id)arg1 voiceSession:(id)arg2;

@end

