//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, OS_dispatch_queue;
@protocol SPTAbbaFeatureFlagsObserver;

@protocol SPTAbbaFeatureFlags <NSObject>
- (void)logAccessForFlagName:(NSString *)arg1;
- (NSString *)objectForKeyedSubscript:(NSString *)arg1;
- (NSString *)stringForKey:(NSString *)arg1;
- (void)removeObserver:(id <SPTAbbaFeatureFlagsObserver>)arg1;
- (void)addObserver:(id <SPTAbbaFeatureFlagsObserver>)arg1 on:(OS_dispatch_queue *)arg2;
- (_Bool)isCacheAvailable;

// Remaining properties
@property(nonatomic, readonly) _Bool cacheAvailable;
@end

