//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPTService-Protocol.h"

@class NSURL;
@protocol SPTAddToSpotifyPlaylistExperimentCellProvider, SPTFreeTierPlaylistDefaultHeaderViewModel, SPTFreeTierPlaylistModel, SPTPlayOrigin, SPTPlayer, SPTPlaylistModel, SPTPlaylistPlatformPlaylistDataLoader, SPTPlaylistRoute;

@protocol SPTAddToSpotifyPlaylistExperimentService <SPTService>
- (_Bool)addToSpotifyPlaylistEnabledForURI:(NSURL *)arg1;
- (_Bool)addToSpotifyPlaylistEnabled;
- (id <SPTPlaylistPlatformPlaylistDataLoader>)provideAddToSpotifyPlaylistDataLoader;
- (id <SPTPlaylistModel>)provideAddToSpotifyPlaylistModel;
- (id <SPTPlaylistRoute>)providePlaylistRouteForURI:(NSURL *)arg1;
- (id <SPTAddToSpotifyPlaylistExperimentCellProvider>)provideCellProviderWithmodel:(id <SPTFreeTierPlaylistModel>)arg1 originalPlaylistViewModel:(id <SPTFreeTierPlaylistDefaultHeaderViewModel>)arg2 player:(id <SPTPlayer>)arg3 playlistURI:(NSURL *)arg4 origin:(id <SPTPlayOrigin>)arg5;
@end

