//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SPTFreeTierPlaylistModelEntityTrackFields;

@interface SPTAddToSpotifyPlaylistExperimentCellModel : NSObject
{
    _Bool _isPlaying;
    id <SPTFreeTierPlaylistModelEntityTrackFields> _track;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isPlaying; // @synthesize isPlaying=_isPlaying;
@property(readonly, nonatomic) id <SPTFreeTierPlaylistModelEntityTrackFields> track; // @synthesize track=_track;
- (unsigned long long)hash;
- (_Bool)isEqualToCellModel:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)initWithTrack:(id)arg1 isPlaying:(_Bool)arg2;

@end

