//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPTService-Protocol.h"

@class NSURL, UIView;
@protocol SPTAddToSpotifyPlaylistExperimentCellProvider, SPTAddToSpotifyPlaylistExperimentLogger, SPTFreeTierPlaylistDefaultHeaderViewModel, SPTFreeTierPlaylistItemsViewModel><SPTFreeTierPlaylistModelObserver, SPTPlayOrigin, SPTPlayer, SPTPlaylistModel, SPTPlaylistPlatformPlaylistDataLoader, SPTPlaylistRoute;

@protocol SPTAddToSpotifyPlaylistExperimentService <SPTService>
- (NSURL *)imageURIForContextURI:(NSURL *)arg1;
- (UIView *)provideAssistedCurationSubtitleViewForURI:(NSURL *)arg1;
- (_Bool)addToSpotifyPlaylistEnabledForURI:(NSURL *)arg1;
- (_Bool)addToSpotifyPlaylistEnabled;
- (id <SPTPlaylistPlatformPlaylistDataLoader>)provideAddToSpotifyPlaylistDataLoader;
- (id <SPTPlaylistModel>)provideAddToSpotifyPlaylistModel;
- (id <SPTPlaylistRoute>)providePlaylistRouteForURI:(NSURL *)arg1;
- (_Bool)shouldRouteForURI:(NSURL *)arg1;
- (id <SPTFreeTierPlaylistItemsViewModel><SPTFreeTierPlaylistModelObserver>)decorateItemsViewModel:(id <SPTFreeTierPlaylistItemsViewModel><SPTFreeTierPlaylistModelObserver>)arg1 forPlaylistURI:(NSURL *)arg2;
- (id <SPTAddToSpotifyPlaylistExperimentCellProvider>)provideCellProviderWithOriginalPlaylistViewModel:(id <SPTFreeTierPlaylistDefaultHeaderViewModel>)arg1 player:(id <SPTPlayer>)arg2 playlistURI:(NSURL *)arg3 origin:(id <SPTPlayOrigin>)arg4 logger:(id <SPTAddToSpotifyPlaylistExperimentLogger>)arg5 viewModelFactory:(id <SPTFreeTierPlaylistModel> (^)(NSURL *))arg6;
@end

