//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTSessionBootstrapDelegate-Protocol.h"

@class NSData;
@protocol SPTEventSender, SPTRemoteConfigurationContext;

@interface SPTBootstrapModule : NSObject <SPTSessionBootstrapDelegate>
{
    id <SPTRemoteConfigurationContext> _remoteConfigurationContext;
    id <SPTEventSender> _eventSender;
    NSData *_remoteConfigurationData;
}

@property(copy, nonatomic) NSData *remoteConfigurationData; // @synthesize remoteConfigurationData=_remoteConfigurationData;
@property(retain, nonatomic) id <SPTEventSender> eventSender; // @synthesize eventSender=_eventSender;
@property(retain, nonatomic) id <SPTRemoteConfigurationContext> remoteConfigurationContext; // @synthesize remoteConfigurationContext=_remoteConfigurationContext;
- (void).cxx_destruct;
- (void)sendNonAuthenticatedEventWithProtobuf:(id)arg1;
- (id)createBootstrapRequestNonAuthWithErrorMessage:(id)arg1 httpCode:(int)arg2 errorReason:(id)arg3 latencyInSeconds:(double)arg4 payloadSize:(long long)arg5;
- (id)createBootstrapRequestNonAuthSuccess:(double)arg1 payloadSize:(long long)arg2;
- (void)parseWebGateResponse:(id)arg1 latencyInSeconds:(double)arg2;
- (id)createBootStrapRequestPayload;
- (id)createWebGateRequest;
- (void)bootstrap:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)provideRemoteConfigurationPayload;
- (id)initWithRemoteConfigurationContext:(id)arg1 eventSender:(id)arg2;

@end

