//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTCoreService-Protocol.h"

@class NSString, SPCore, SPTAllocationContext, SPTBootstrapCoreProxyImplementation, SPTConnectivityApplicationScope, SPTConnectivityManager, SPTCoreLogHandler, SPTCoreLoggerConnectivityAnalyticsDelegate, SPTCoreSchedulerThread, SPTEventSenderAnalyticsDelegate, SPTEventSenderCoreProxyImplementation, SPTPreferencesImplementation;
@protocol SPTAudioDriverController, SPTAuthCredentialsStorage, SPTConnectivityConnectionTypeProvider, SPTConnectivityConnectivityPolicyProvider;

@interface SPTCoreServiceImplementation : NSObject <SPTCoreService>
{
    id <SPTAudioDriverController> _audioDriverController;
    SPTCoreLogHandler *_logHandler;
    SPTEventSenderCoreProxyImplementation *_eventSenderCoreProxy;
    SPTBootstrapCoreProxyImplementation *_bootstrapCoreProxy;
    SPTCoreSchedulerThread *_coreScheduler;
    SPTPreferencesImplementation *_preferences;
    SPTCoreLoggerConnectivityAnalyticsDelegate *_connectivityAnalyticsDelegate;
    id <SPTConnectivityConnectionTypeProvider> _connectivityConnectionTypeProvider;
    id <SPTConnectivityConnectivityPolicyProvider> _connectivityConnectivityPolicyProvider;
    id <SPTAuthCredentialsStorage> _connectivityCredentialsStorage;
    SPTConnectivityManager *_connectivityManager;
    SPTConnectivityApplicationScope *_connectivityApplicationScope;
    SPTEventSenderAnalyticsDelegate *_eventSenderAnalyticsDelegate;
    SPCore *_core;
    CDUnknownBlockType _assertionHandlerCallback;
}

+ (id)serviceIdentifier;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType assertionHandlerCallback; // @synthesize assertionHandlerCallback=_assertionHandlerCallback;
@property(retain, nonatomic) SPCore *core; // @synthesize core=_core;
@property(retain, nonatomic) SPTEventSenderAnalyticsDelegate *eventSenderAnalyticsDelegate; // @synthesize eventSenderAnalyticsDelegate=_eventSenderAnalyticsDelegate;
@property(retain, nonatomic) SPTConnectivityApplicationScope *connectivityApplicationScope; // @synthesize connectivityApplicationScope=_connectivityApplicationScope;
@property(retain, nonatomic) SPTConnectivityManager *connectivityManager; // @synthesize connectivityManager=_connectivityManager;
@property(retain, nonatomic) id <SPTAuthCredentialsStorage> connectivityCredentialsStorage; // @synthesize connectivityCredentialsStorage=_connectivityCredentialsStorage;
@property(retain, nonatomic) id <SPTConnectivityConnectivityPolicyProvider> connectivityConnectivityPolicyProvider; // @synthesize connectivityConnectivityPolicyProvider=_connectivityConnectivityPolicyProvider;
@property(retain, nonatomic) id <SPTConnectivityConnectionTypeProvider> connectivityConnectionTypeProvider; // @synthesize connectivityConnectionTypeProvider=_connectivityConnectionTypeProvider;
@property(retain, nonatomic) SPTCoreLoggerConnectivityAnalyticsDelegate *connectivityAnalyticsDelegate; // @synthesize connectivityAnalyticsDelegate=_connectivityAnalyticsDelegate;
@property(retain, nonatomic) SPTPreferencesImplementation *preferences; // @synthesize preferences=_preferences;
@property(retain, nonatomic) SPTCoreSchedulerThread *coreScheduler; // @synthesize coreScheduler=_coreScheduler;
@property(retain, nonatomic) SPTBootstrapCoreProxyImplementation *bootstrapCoreProxy; // @synthesize bootstrapCoreProxy=_bootstrapCoreProxy;
@property(retain, nonatomic) SPTEventSenderCoreProxyImplementation *eventSenderCoreProxy; // @synthesize eventSenderCoreProxy=_eventSenderCoreProxy;
@property(retain, nonatomic) SPTCoreLogHandler *logHandler; // @synthesize logHandler=_logHandler;
@property(retain, nonatomic) id <SPTAudioDriverController> audioDriverController; // @synthesize audioDriverController=_audioDriverController;
- (id)settingsPath;
- (id)persistentCachePath;
- (id)volatileCachePath;
- (id)persistentCacheRoot;
- (id)volatileCacheRoot;
- (void)markForBackupExclusion:(id)arg1;
- (void)migrateCachesFromPath:(id)arg1 persistentPath:(id)arg2 volatilePath:(id)arg3;
- (id)legacyCachePath;
- (void)createAndMigratePathsForPersistentCache:(id)arg1 volatileCache:(id)arg2 settings:(id)arg3;
- (void)setupCoreWithAudioDriverController:(id)arg1;
- (void)setBootstrapModule:(id)arg1;
- (void)setEventSenderCore:(id)arg1;
- (id)provideAudioDriverController;
- (id)provideCoreLogDispatcher;
- (id)provideCoreInstance;
- (void)unload;
- (void)load;
- (void)configureWithServices:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

