//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface SPTDeferredBlockDispatcher : NSObject
{
    NSMutableDictionary *_deferredBlocks;
    CDUnknownBlockType _dispatchConditionBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType dispatchConditionBlock; // @synthesize dispatchConditionBlock=_dispatchConditionBlock;
@property(retain, nonatomic) NSMutableDictionary *deferredBlocks; // @synthesize deferredBlocks=_deferredBlocks;
- (void)dispatchBlocksForKey:(id)arg1;
- (void)deferBlock:(CDUnknownBlockType)arg1 forKey:(id)arg2;
- (id)initWithDispatchCondition:(CDUnknownBlockType)arg1;

@end

