//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTDataLoaderAuthorisationHostRegistration-Protocol.h"
#import "SPTDataLoaderAuthoriser-Protocol.h"

@class NSString;
@protocol SPTClientTokenAcquirer, SPTDataLoaderAuthoriserDelegate;

@interface SPTDataLoaderClientTokenAuthoriser : NSObject <SPTDataLoaderAuthoriser, SPTDataLoaderAuthorisationHostRegistration>
{
    id <SPTDataLoaderAuthoriserDelegate> delegate;
    NSString *identifier;
    id <SPTClientTokenAcquirer> _clientTokenAcquirer;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <SPTClientTokenAcquirer> clientTokenAcquirer; // @synthesize clientTokenAcquirer=_clientTokenAcquirer;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier;
@property(nonatomic) __weak id <SPTDataLoaderAuthoriserDelegate> delegate; // @synthesize delegate;
- (void)unregisterAuthorisationHostsName:(id)arg1;
- (void)registerAuthorisationHosts:(id)arg1 withName:(id)arg2;
- (_Bool)requestRequiresAuthorisation:(id)arg1;
- (void)requestFailedAuthorisation:(id)arg1;
- (void)refresh;
- (void)authoriseRequest:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithClientTokenAcquirer:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

