//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "INTERNAL_SPTEncorePlaylistHeaderPersonalizedModel.h"

@interface SPTEncorePlaylistHeaderPersonalizedModel : INTERNAL_SPTEncorePlaylistHeaderPersonalizedModel
{
}

- (id)initWithName:(id)arg1 userName:(id)arg2 playlistDescription:(id)arg3 coverArtImage:(id)arg4 coverArtColor:(id)arg5 likes:(long long)arg6 duration:(double)arg7 downloadState:(long long)arg8 isPlaying:(_Bool)arg9 isPlayable:(_Bool)arg10 isLikeable:(_Bool)arg11 isDownloadable:(_Bool)arg12 showsShuffleBadge:(_Bool)arg13 isLiked:(_Bool)arg14 minimumHeight:(double)arg15 fullHeight:(double)arg16;

@end

