//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class UIView;

@protocol SPTEncoreAlbumHeaderDelegate
- (void)backButtonTappedWithSender:(UIView *)arg1;
- (void)pauseWithSender:(UIView *)arg1;
- (void)playWithSender:(UIView *)arg1;
- (void)creatorTappedWithSender:(UIView *)arg1;
- (void)cancelDownloadWithSender:(UIView *)arg1;
- (void)downloadWithSender:(UIView *)arg1;
- (void)unlikeWithSender:(UIView *)arg1;
- (void)likeWithSender:(UIView *)arg1;
- (void)contextMenuTappedWithSender:(UIView *)arg1;
@end

