//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "INTERNAL_SPTEncoreEpisodeRowListeningHistoryModel.h"

@interface SPTEncoreEpisodeRowListeningHistoryModel : INTERNAL_SPTEncoreEpisodeRowListeningHistoryModel
{
}

- (id)initWithEpisodeTitle:(id)arg1 showTitle:(id)arg2 coverArtUri:(id)arg3 isPlaying:(_Bool)arg4;

@end

