//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL;
@protocol SPTUBIMobilePlaylistExtenderEventFactory, SPTUserBehaviourInstrumentationLogger;

@interface SPTFreeTierPlaylistPlexLogger : NSObject
{
    id <SPTUserBehaviourInstrumentationLogger> _ubiLogger;
    id <SPTUBIMobilePlaylistExtenderEventFactory> _ubiEventFactory;
    NSURL *_playlistURL;
}

@property(readonly, nonatomic) NSURL *playlistURL; // @synthesize playlistURL=_playlistURL;
@property(readonly, nonatomic) id <SPTUBIMobilePlaylistExtenderEventFactory> ubiEventFactory; // @synthesize ubiEventFactory=_ubiEventFactory;
@property(readonly, nonatomic) id <SPTUserBehaviourInstrumentationLogger> ubiLogger; // @synthesize ubiLogger=_ubiLogger;
- (void).cxx_destruct;
- (void)addItemToPlaylistWithTrackURI:(id)arg1;
- (void)playItemWithTrackURI:(id)arg1;
- (void)refreshButtonPressed;
- (id)initWithUbiEventFactory:(id)arg1 ubiLogger:(id)arg2 playlistURL:(id)arg3;

@end

