//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSURL;
@protocol SPTFreeTierCreatePlaylistController;

@protocol SPTFreeTierCreatePlaylistControllerDelegate <NSObject>
- (void)createPlaylistControllerDidCancel:(id <SPTFreeTierCreatePlaylistController>)arg1;
- (void)createPlaylistController:(id <SPTFreeTierCreatePlaylistController>)arg1 didRenamePlaylistURL:(NSURL *)arg2;
- (void)createPlaylistController:(id <SPTFreeTierCreatePlaylistController>)arg1 didCreatePlaylistURL:(NSURL *)arg2;
@end

