//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SPTHubLogger, SPTUBIMobileAlbumPageEventFactory;

@interface SPTFreeTierAlbumUBILogger : NSObject
{
    id <SPTHubLogger> _logger;
    id <SPTUBIMobileAlbumPageEventFactory> _eventFactory;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <SPTUBIMobileAlbumPageEventFactory> eventFactory; // @synthesize eventFactory=_eventFactory;
@property(readonly, nonatomic) id <SPTHubLogger> logger; // @synthesize logger=_logger;
- (void)logSwipeRightAddToQueueWithPosition:(long long)arg1 targetURI:(id)arg2;
- (void)logSwipeLeftRemoveLikeWithPosition:(long long)arg1 targetURI:(id)arg2;
- (void)logSwipeLeftLikeWithPosition:(long long)arg1 targetURI:(id)arg2;
- (id)initWithLogger:(id)arg1 eventFactory:(id)arg2;

@end

