//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTFormatListPlatformService-Protocol.h"
#import "SPTService-Protocol.h"

@class NSString, SPTAllocationContext, SPTFormatListPlatformRegistryImplementation, SPTFormatListPlatformTestManagerImplementation;
@protocol SPTAbbaService, SPTAlgotorialSharingService, SPTCoreService, SPTFormatListPlatformResolver, SPTFreeTierService, SPTGLUEService, SPTLocalSettings, SPTPlaylistPlatformService, SPTSessionService, SPTVisualRefreshIntegrationService, VISREFIntegrationManager;

@interface SPTFormatListPlatformServiceImplementation : NSObject <SPTService, SPTFormatListPlatformService>
{
    id <SPTSessionService> _clientSessionService;
    id <SPTFreeTierService> _freeTierService;
    id <SPTGLUEService> _glueService;
    id <SPTCoreService> _coreService;
    id <SPTAbbaService> _abbaService;
    id <SPTPlaylistPlatformService> _playlistPlatformService;
    id <SPTAlgotorialSharingService> _algotorialSharingService;
    id <SPTVisualRefreshIntegrationService> _visualRefreshIntegrationService;
    id <VISREFIntegrationManager> _visualRefreshIntegrationManager;
    SPTFormatListPlatformTestManagerImplementation *_testManager;
    SPTFormatListPlatformRegistryImplementation *_registry;
    id <SPTFormatListPlatformResolver> _platformResolver;
    id <SPTLocalSettings> _localSettings;
}

+ (id)serviceIdentifier;
- (void).cxx_destruct;
@property(retain, nonatomic) id <SPTLocalSettings> localSettings; // @synthesize localSettings=_localSettings;
@property(retain, nonatomic) id <SPTFormatListPlatformResolver> platformResolver; // @synthesize platformResolver=_platformResolver;
@property(retain, nonatomic) SPTFormatListPlatformRegistryImplementation *registry; // @synthesize registry=_registry;
@property(retain, nonatomic) SPTFormatListPlatformTestManagerImplementation *testManager; // @synthesize testManager=_testManager;
@property(retain, nonatomic) id <VISREFIntegrationManager> visualRefreshIntegrationManager; // @synthesize visualRefreshIntegrationManager=_visualRefreshIntegrationManager;
@property(nonatomic) __weak id <SPTVisualRefreshIntegrationService> visualRefreshIntegrationService; // @synthesize visualRefreshIntegrationService=_visualRefreshIntegrationService;
@property(nonatomic) __weak id <SPTAlgotorialSharingService> algotorialSharingService; // @synthesize algotorialSharingService=_algotorialSharingService;
@property(nonatomic) __weak id <SPTPlaylistPlatformService> playlistPlatformService; // @synthesize playlistPlatformService=_playlistPlatformService;
@property(nonatomic) __weak id <SPTAbbaService> abbaService; // @synthesize abbaService=_abbaService;
@property(nonatomic) __weak id <SPTCoreService> coreService; // @synthesize coreService=_coreService;
@property(nonatomic) __weak id <SPTGLUEService> glueService; // @synthesize glueService=_glueService;
@property(nonatomic) __weak id <SPTFreeTierService> freeTierService; // @synthesize freeTierService=_freeTierService;
@property(nonatomic) __weak id <SPTSessionService> clientSessionService; // @synthesize clientSessionService=_clientSessionService;
- (id)providePlatformManagerForFormatListURL:(id)arg1;
- (id)providePlatformResolver;
- (id)providePlatformRegistry;
- (id)provideLocalSettings;
- (id)provideTestManager;
- (id)provideFormatListPlatformViewController:(id)arg1 context:(id)arg2;
- (void)load;
- (void)configureWithServices:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

