//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, NSURL;

@protocol SPTFreeTierPlaylistDefaultHeaderViewModel <NSObject>
- (void)navigateToPlaylistOwnerPage;
- (_Bool)isFormatList;
@property(nonatomic, readonly) NSString *playlistOwnerName;
@property(nonatomic, readonly) NSURL *ownerImageURL;
@property(nonatomic, readonly) _Bool showSearchBar;
@property(nonatomic, readonly) NSURL *playlistImageURL;
@property(nonatomic, readonly) NSString *playlistDescription;
@property(nonatomic, readonly) NSString *playlistName;

// Remaining properties
@property(nonatomic, readonly) _Bool formatList;
@end

