//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTGaiaDevicePickerDeviceSpecificConfigurationProvider-Protocol.h"

@class NSString, UIViewController;

@interface SPTGaiaDevicePickerDeviceSpecificConfigurationManager : NSObject <SPTGaiaDevicePickerDeviceSpecificConfigurationProvider>
{
    UIViewController *_mainViewController;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIViewController *mainViewController; // @synthesize mainViewController=_mainViewController;
@property(readonly, nonatomic) _Bool devicePickerCanBeAccessedAsStandalonePage;
@property(readonly, nonatomic) _Bool devicePickerWantsPopoverPresentation;
@property(readonly, nonatomic) _Bool devicePickerWantsLightTheme;
- (id)initWithMainViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

