//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SPTDataLoaderFactory, SPTHomeContentStorage;
@protocol SPTCrashReporter, SPTFeatureSettingsItemFactory, SPTFreeTierTasteOnboardingCurationProvider, SPTNetworkConnectivityController, SPTOfflineService, SPTOnDemandService, SPTPlayer, SPTRecentlyPlayedService, SPTUBIHubsUtilities;

@interface SPTHomeContentOperationFactory : NSObject
{
    id <SPTOnDemandService> _onDemandService;
    id <SPTRecentlyPlayedService> _recentlyPlayedService;
    id <SPTOfflineService> _offlineService;
    id <SPTNetworkConnectivityController> _networkConnectivityController;
    SPTHomeContentStorage *_homeContentStorage;
    SPTDataLoaderFactory *_dataLoaderFactory;
    id <SPTPlayer> _player;
    id <SPTFreeTierTasteOnboardingCurationProvider> _tasteOnboardingCurationProvider;
    id <SPTFeatureSettingsItemFactory> _featureSettingsItemFactory;
    id <SPTUBIHubsUtilities> _ubiHubsInstrumentation;
    id <SPTCrashReporter> _crashReporter;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <SPTCrashReporter> crashReporter; // @synthesize crashReporter=_crashReporter;
@property(readonly, nonatomic) id <SPTUBIHubsUtilities> ubiHubsInstrumentation; // @synthesize ubiHubsInstrumentation=_ubiHubsInstrumentation;
@property(readonly, nonatomic) id <SPTFeatureSettingsItemFactory> featureSettingsItemFactory; // @synthesize featureSettingsItemFactory=_featureSettingsItemFactory;
@property(readonly, nonatomic) id <SPTFreeTierTasteOnboardingCurationProvider> tasteOnboardingCurationProvider; // @synthesize tasteOnboardingCurationProvider=_tasteOnboardingCurationProvider;
@property(readonly, nonatomic) id <SPTPlayer> player; // @synthesize player=_player;
@property(readonly, nonatomic) SPTDataLoaderFactory *dataLoaderFactory; // @synthesize dataLoaderFactory=_dataLoaderFactory;
@property(readonly, nonatomic) SPTHomeContentStorage *homeContentStorage; // @synthesize homeContentStorage=_homeContentStorage;
@property(readonly, nonatomic) id <SPTNetworkConnectivityController> networkConnectivityController; // @synthesize networkConnectivityController=_networkConnectivityController;
@property(readonly, nonatomic) __weak id <SPTOfflineService> offlineService; // @synthesize offlineService=_offlineService;
@property(readonly, nonatomic) __weak id <SPTRecentlyPlayedService> recentlyPlayedService; // @synthesize recentlyPlayedService=_recentlyPlayedService;
@property(readonly, nonatomic) __weak id <SPTOnDemandService> onDemandService; // @synthesize onDemandService=_onDemandService;
- (id)provideCacheViewModelContentOperation;
- (id)provideDownloadsContentOperation;
- (id)provideRemoteContentOperationWithSourceIdentifier:(id)arg1 contentURL:(id)arg2;
- (id)provideCachedContentOperation;
- (id)provideRemoveComponentContentOperationWithOverrides:(id)arg1;
- (id)provideOnDemandExtractorContentOperation;
- (id)provideOnDemandDecoratorContentOperation;
- (id)provideCardAccessibilityContentOperation;
- (id)provideRecentlyPlayedContentOperation;
- (id)initWithOnDemandService:(id)arg1 recentlyPlayedService:(id)arg2 offlineService:(id)arg3 networkConnectivityController:(id)arg4 homeContentStorage:(id)arg5 dataLoaderFactory:(id)arg6 player:(id)arg7 tasteOnboardingCurationProvider:(id)arg8 featureSettingsItemFactory:(id)arg9 ubiHubsInstrumentation:(id)arg10 crashReporter:(id)arg11;

@end

