//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "HUBOverlayViewComponentDelegate-Protocol.h"
#import "HUBViewComponentDelegate-Protocol.h"
#import "HUBViewContentOffsetObserver-Protocol.h"
#import "SPTContentBottomLayoutGuideObserver-Protocol.h"
#import "SPTHomeViewModelProviderObserver-Protocol.h"
#import "SPTHubViewModelProviderDelegate-Protocol.h"
#import "SPTNavigationControllerNavigationBarState-Protocol.h"
#import "SPTOfflineModeStateObserver-Protocol.h"
#import "SPTPageController-Protocol.h"
#import "SPTScrollToTopViewController-Protocol.h"
#import "SPViewController-Protocol.h"

@class NSArray, NSMutableDictionary, NSString, NSURL, SPTHomeLocalViewModelOverrides, SPTHomeNavigationItemDecorator, SPTHomeStatusBarAppearanceModifier, SPTHomeView, SPTHomeViewModelProvider;
@protocol HUBViewModel, SPTHubImpressionLogger, SPTOfflineModeState, SPTPageContainer, SPTShareDragDelegateFactory;

@interface SPTHomeViewController : UIViewController <SPTContentBottomLayoutGuideObserver, SPTScrollToTopViewController, HUBViewContentOffsetObserver, SPTHubViewModelProviderDelegate, HUBOverlayViewComponentDelegate, HUBViewComponentDelegate, SPTOfflineModeStateObserver, SPTPageController, SPTNavigationControllerNavigationBarState, SPViewController, SPTHomeViewModelProviderObserver>
{
    _Bool _currentlyOffline;
    NSString *_pageIdentifier;
    NSURL *_pageURI;
    SPTHomeNavigationItemDecorator *_navigationItemDecorator;
    NSURL *_viewURI;
    id <SPTHubImpressionLogger> _hubImpressionLogger;
    SPTHomeViewModelProvider *_viewModelProvider;
    id <SPTShareDragDelegateFactory> _shareDragDelegateFactory;
    id <SPTOfflineModeState> _offlineState;
    SPTHomeLocalViewModelOverrides *_overrides;
    SPTHomeStatusBarAppearanceModifier *_statusBarAppearanceModifier;
    id <HUBViewModel> _initialViewModel;
    CDUnknownBlockType _homeViewFactory;
    NSMutableDictionary *_dragDelegateHolders;
    double _navigationbarAlpha;
    NSArray *_observers;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSArray *observers; // @synthesize observers=_observers;
@property(nonatomic) double navigationbarAlpha; // @synthesize navigationbarAlpha=_navigationbarAlpha;
@property(nonatomic, getter=isCurrentlyOffline) _Bool currentlyOffline; // @synthesize currentlyOffline=_currentlyOffline;
@property(retain, nonatomic) NSMutableDictionary *dragDelegateHolders; // @synthesize dragDelegateHolders=_dragDelegateHolders;
@property(readonly, copy, nonatomic) CDUnknownBlockType homeViewFactory; // @synthesize homeViewFactory=_homeViewFactory;
@property(retain, nonatomic) id <HUBViewModel> initialViewModel; // @synthesize initialViewModel=_initialViewModel;
@property(readonly, nonatomic) SPTHomeStatusBarAppearanceModifier *statusBarAppearanceModifier; // @synthesize statusBarAppearanceModifier=_statusBarAppearanceModifier;
@property(readonly, nonatomic) SPTHomeLocalViewModelOverrides *overrides; // @synthesize overrides=_overrides;
@property(readonly, nonatomic) id <SPTOfflineModeState> offlineState; // @synthesize offlineState=_offlineState;
@property(readonly, nonatomic) id <SPTShareDragDelegateFactory> shareDragDelegateFactory; // @synthesize shareDragDelegateFactory=_shareDragDelegateFactory;
@property(readonly, nonatomic) SPTHomeViewModelProvider *viewModelProvider; // @synthesize viewModelProvider=_viewModelProvider;
@property(readonly, nonatomic) id <SPTHubImpressionLogger> hubImpressionLogger; // @synthesize hubImpressionLogger=_hubImpressionLogger;
@property(readonly, copy, nonatomic) NSURL *viewURI; // @synthesize viewURI=_viewURI;
@property(retain, nonatomic) SPTHomeNavigationItemDecorator *navigationItemDecorator; // @synthesize navigationItemDecorator=_navigationItemDecorator;
@property(readonly, nonatomic, getter=spt_pageIdentifier) NSString *pageIdentifier; // @synthesize pageIdentifier=_pageIdentifier;
- (void)offlineModeState:(id)arg1 updated:(_Bool)arg2;
- (id)shareDragDelegateWithModel:(id)arg1;
- (void)sp_updateContentInsets;
- (void)layoutGuideChanged;
- (void)overlayView:(id)arg1 componentViewDidDisappear:(id)arg2;
- (void)overlayView:(id)arg1 componentViewWillAppear:(id)arg2;
- (void)hubView:(id)arg1 componentViewDidDisappear:(id)arg2;
- (void)hubView:(id)arg1 componentViewWillAppear:(id)arg2;
- (void)updateNavigationBarAlpha;
- (void)spt_scrollToTop;
- (void)loadViewModelForOfflineState:(_Bool)arg1;
- (void)addViewObserver:(id)arg1;
- (void)contentSizeCategoryDidChange;
- (void)hubView:(id)arg1 contentOffsetDidChange:(struct CGPoint)arg2;
- (unsigned long long)preferredNavigationBarState;
@property(readonly, nonatomic, getter=spt_pageURI) NSURL *pageURI; // @synthesize pageURI=_pageURI;
@property(readonly, nonatomic) NSURL *URI;
- (void)updateViewWithViewModel:(id)arg1;
- (void)viewModelProvider:(id)arg1 didLoadRemoteViewModel:(id)arg2 withError:(id)arg3;
- (void)viewModelProviderWillLoadRemoteViewModel:(id)arg1;
- (void)viewModelProvider:(id)arg1 didLoadCachedViewModel:(id)arg2 withError:(id)arg3;
- (void)viewModelProviderWillLoadCachedViewModel:(id)arg1;
- (void)viewModelDidLoad:(id)arg1 dataSource:(unsigned long long)arg2;
- (void)viewModelDidLoad:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithViewURI:(id)arg1 hubImpressionLogger:(id)arg2 viewModelProvider:(id)arg3 shareDragDelegateFactory:(id)arg4 offlineState:(id)arg5 overrides:(id)arg6 statusBarAppearanceModifier:(id)arg7 initialViewModel:(id)arg8 homeViewFactory:(CDUnknownBlockType)arg9;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=spt_pageContainer) id <SPTPageContainer> pageContainer;
@property(readonly) Class superclass;
@property(retain, nonatomic) SPTHomeView *view; // @dynamic view;

@end

