//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SPTHubViewModelProvider;
@protocol HUBViewModel;

@interface SPTHubLoadableResult : NSObject
{
    SPTHubViewModelProvider *_viewModelProvider;
    id <HUBViewModel> _initialViewModel;
}

@property(readonly, nonatomic) id <HUBViewModel> initialViewModel; // @synthesize initialViewModel=_initialViewModel;
@property(readonly, nonatomic) SPTHubViewModelProvider *viewModelProvider; // @synthesize viewModelProvider=_viewModelProvider;
- (void).cxx_destruct;
- (id)initWithViewModelProvider:(id)arg1 initialViewModel:(id)arg2;

@end

