//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class HUBComponentDefaults, SPTHomeContentOperationFactory;
@protocol SPTHugsFactory;

@interface SPTHomeViewModelLoaderFactory : NSObject
{
    SPTHomeContentOperationFactory *_contentOperationFactory;
    id <SPTHugsFactory> _hugsFactory;
    HUBComponentDefaults *_componentDefaults;
}

- (void).cxx_destruct;
@property(retain, nonatomic) HUBComponentDefaults *componentDefaults; // @synthesize componentDefaults=_componentDefaults;
@property(readonly, nonatomic) id <SPTHugsFactory> hugsFactory; // @synthesize hugsFactory=_hugsFactory;
@property(readonly, nonatomic) SPTHomeContentOperationFactory *contentOperationFactory; // @synthesize contentOperationFactory=_contentOperationFactory;
- (id)createRemoteViewModelLoaderForContentURL:(id)arg1 sourceIdentifier:(id)arg2 overrides:(id)arg3;
- (id)createCachedViewModelLoaderWithOverrides:(id)arg1;
- (id)initWithContentOperationFactory:(id)arg1 hugsFactory:(id)arg2;

@end

