//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTRemoteConfigurationProperties-Protocol.h"

@class NSString;

@interface SPTHomeFeatureProperties : NSObject <SPTRemoteConfigurationProperties>
{
    _Bool _useNewCacheLocation;
    _Bool _homeImprovedNavigationBar;
    _Bool _solidHeaderBackground;
    _Bool _isPageloaderEnabled;
}

@property(readonly, nonatomic) _Bool isPageloaderEnabled; // @synthesize isPageloaderEnabled=_isPageloaderEnabled;
@property(readonly, nonatomic) _Bool solidHeaderBackground; // @synthesize solidHeaderBackground=_solidHeaderBackground;
@property(readonly, nonatomic) _Bool homeImprovedNavigationBar; // @synthesize homeImprovedNavigationBar=_homeImprovedNavigationBar;
@property(readonly, nonatomic) _Bool useNewCacheLocation; // @synthesize useNewCacheLocation=_useNewCacheLocation;
- (id)propertyModels;
- (id)initWithPropertyValuesDictionary:(id)arg1;
- (id)initWithConfiguration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

