//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTFeatureFlagSignalObserver-Protocol.h"

@class NSString, SPTHomeFeatureProperties;
@protocol SPTFeatureFlagFactory, SPTFeatureFlagSignal, SPTFeatureSettingsItemFactory, SPTLocalSettings;

@interface SPTHomeRemoteConfigPropertyResolver : NSObject <SPTFeatureFlagSignalObserver>
{
    _Bool _solidHeaderBackgroundEnabled;
    id <SPTFeatureFlagFactory> _featureFlagFactory;
    id <SPTFeatureSettingsItemFactory> _featureSettingsItemFactory;
    SPTHomeFeatureProperties *_rcsProperties;
    id <SPTLocalSettings> _localSettings;
    id <SPTFeatureFlagSignal> _homeSolidBackgroundEnabledSignal;
}

@property(readonly, nonatomic) id <SPTFeatureFlagSignal> homeSolidBackgroundEnabledSignal; // @synthesize homeSolidBackgroundEnabledSignal=_homeSolidBackgroundEnabledSignal;
@property(readonly, nonatomic) id <SPTLocalSettings> localSettings; // @synthesize localSettings=_localSettings;
@property(readonly, nonatomic) SPTHomeFeatureProperties *rcsProperties; // @synthesize rcsProperties=_rcsProperties;
@property(readonly, nonatomic) id <SPTFeatureSettingsItemFactory> featureSettingsItemFactory; // @synthesize featureSettingsItemFactory=_featureSettingsItemFactory;
@property(readonly, nonatomic) id <SPTFeatureFlagFactory> featureFlagFactory; // @synthesize featureFlagFactory=_featureFlagFactory;
@property(nonatomic, getter=isSolidHeaderBackgroundEnabled) _Bool solidHeaderBackgroundEnabled; // @synthesize solidHeaderBackgroundEnabled=_solidHeaderBackgroundEnabled;
- (void).cxx_destruct;
- (void)featureFlagSignal:(id)arg1 hasAssumedState:(long long)arg2;
- (void)setupFlagSignals;
- (void)initFlags;
- (void)dealloc;
- (id)initWithFeatureFlagFactory:(id)arg1 featureSettingsItemFactory:(id)arg2 rcsProperties:(id)arg3 localSettings:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

