//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTFeatureFlagSignalObserver-Protocol.h"

@class NSString;
@protocol SPTFeatureFlagFactory, SPTFeatureFlagSignal;

@interface SPTInAppMessageFeatureFlagChecks : NSObject <SPTFeatureFlagSignalObserver>
{
    _Bool _feedbackEnabled;
    _Bool _inAppMessageFollowTriggerEnabled;
    _Bool _inAppMessageDownloadTriggerEnabled;
    id <SPTFeatureFlagSignal> _feedbackFlagSignal;
    id <SPTFeatureFlagSignal> _inAppMessagingFollowTriggerFlagSignal;
    id <SPTFeatureFlagSignal> _inAppMessagingDownloadTriggerFlagSignal;
    id <SPTFeatureFlagFactory> _featureFlagFactory;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <SPTFeatureFlagFactory> featureFlagFactory; // @synthesize featureFlagFactory=_featureFlagFactory;
@property(nonatomic, getter=isInAppMessageDownloadTriggerEnabled) _Bool inAppMessageDownloadTriggerEnabled; // @synthesize inAppMessageDownloadTriggerEnabled=_inAppMessageDownloadTriggerEnabled;
@property(nonatomic, getter=isInAppMessageFollowTriggerEnabled) _Bool inAppMessageFollowTriggerEnabled; // @synthesize inAppMessageFollowTriggerEnabled=_inAppMessageFollowTriggerEnabled;
@property(nonatomic, getter=isFeedbackEnabled) _Bool feedbackEnabled; // @synthesize feedbackEnabled=_feedbackEnabled;
@property(readonly, nonatomic) id <SPTFeatureFlagSignal> inAppMessagingDownloadTriggerFlagSignal; // @synthesize inAppMessagingDownloadTriggerFlagSignal=_inAppMessagingDownloadTriggerFlagSignal;
@property(readonly, nonatomic) id <SPTFeatureFlagSignal> inAppMessagingFollowTriggerFlagSignal; // @synthesize inAppMessagingFollowTriggerFlagSignal=_inAppMessagingFollowTriggerFlagSignal;
@property(readonly, nonatomic) id <SPTFeatureFlagSignal> feedbackFlagSignal; // @synthesize feedbackFlagSignal=_feedbackFlagSignal;
- (void)featureFlagSignal:(id)arg1 hasAssumedState:(long long)arg2;
- (id)featureFlagSignalWithABBAKey:(id)arg1 defaultState:(long long)arg2 abbaEnabledValue:(id)arg3;
- (void)setupInAppMessageABBAFlags;
- (void)dealloc;
- (id)initWithFeatureFlagFactory:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

