//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableArray, SPTInAppMessageServiceLogger;
@protocol SPTContextMenuPresenter, SPTContextMenuPresenterFactory;

@interface SPTInAppMessageFeedbackPresentationController : NSObject
{
    _Bool _feedbackOptionsSet;
    NSMutableArray *_contextMenuActions;
    NSDictionary *_messageInformation;
    id <SPTContextMenuPresenterFactory> _contextMenuPresenterFactory;
    id <SPTContextMenuPresenter> _contextMenuPresenter;
    SPTInAppMessageServiceLogger *_serviceLogger;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool feedbackOptionsSet; // @synthesize feedbackOptionsSet=_feedbackOptionsSet;
@property(retain, nonatomic) SPTInAppMessageServiceLogger *serviceLogger; // @synthesize serviceLogger=_serviceLogger;
@property(retain, nonatomic) id <SPTContextMenuPresenter> contextMenuPresenter; // @synthesize contextMenuPresenter=_contextMenuPresenter;
@property(retain, nonatomic) id <SPTContextMenuPresenterFactory> contextMenuPresenterFactory; // @synthesize contextMenuPresenterFactory=_contextMenuPresenterFactory;
@property(copy, nonatomic) NSDictionary *messageInformation; // @synthesize messageInformation=_messageInformation;
@property(retain, nonatomic) NSMutableArray *contextMenuActions; // @synthesize contextMenuActions=_contextMenuActions;
- (void)setFeedbackOptions:(id)arg1;
- (void)presentFeedbackUIForMessage:(id)arg1 inViewController:(id)arg2 senderView:(id)arg3;
- (id)initWithContextMenuPresenterFactory:(id)arg1 serviceLogger:(id)arg2;

@end

