//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SPTImageResolveProjectionMapLoader;

@interface SPTImageResolveManager : NSObject
{
    SPTImageResolveProjectionMapLoader *_loader;
}

@property(readonly, nonatomic) SPTImageResolveProjectionMapLoader *loader; // @synthesize loader=_loader;
- (void).cxx_destruct;
- (id)createImageResolver;
- (void)loadConfiguration;
- (id)initWithTransport:(id)arg1 userIdentifier:(id)arg2 configurationTTL:(unsigned long long)arg3;

@end

