//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTLoginAppleAuthorizationControllerDelegate-Protocol.h"
#import "SPTLoginFacebookAuthenticationControllerDelegate-Protocol.h"

@class NSString, SPTDynamicSignupFlowController, SPTLoginAppleAuthorizationController, SPTLoginDbManager, SPTLoginErrorDecorator, SPTLoginFacebookAuthenticationController, SPTLoginWelcomeViewLogger;
@protocol SPTDialogController, SPTLoginStateController, SPTLoginWelcomeViewModelDelegate;

@interface SPTLoginWelcomeViewModel : NSObject <SPTLoginFacebookAuthenticationControllerDelegate, SPTLoginAppleAuthorizationControllerDelegate>
{
    _Bool _savedCredentialsDialogShownOnce;
    id <SPTLoginWelcomeViewModelDelegate> _delegate;
    SPTLoginWelcomeViewLogger *_logger;
    id <SPTLoginStateController> _loginStateController;
    SPTLoginErrorDecorator *_errorDecorator;
    SPTLoginFacebookAuthenticationController *_facebookAuthController;
    SPTLoginAppleAuthorizationController *_appleAuthController;
    id <SPTDialogController> _dialogController;
    SPTDynamicSignupFlowController *_flowController;
    SPTLoginDbManager *_databaseManager;
}

@property(readonly, nonatomic) SPTLoginDbManager *databaseManager; // @synthesize databaseManager=_databaseManager;
@property(readonly, nonatomic) SPTDynamicSignupFlowController *flowController; // @synthesize flowController=_flowController;
@property(nonatomic) _Bool savedCredentialsDialogShownOnce; // @synthesize savedCredentialsDialogShownOnce=_savedCredentialsDialogShownOnce;
@property(readonly, nonatomic) id <SPTDialogController> dialogController; // @synthesize dialogController=_dialogController;
@property(readonly, nonatomic) SPTLoginAppleAuthorizationController *appleAuthController; // @synthesize appleAuthController=_appleAuthController;
@property(readonly, nonatomic) SPTLoginFacebookAuthenticationController *facebookAuthController; // @synthesize facebookAuthController=_facebookAuthController;
@property(readonly, nonatomic) SPTLoginErrorDecorator *errorDecorator; // @synthesize errorDecorator=_errorDecorator;
@property(readonly, nonatomic) id <SPTLoginStateController> loginStateController; // @synthesize loginStateController=_loginStateController;
@property(readonly, nonatomic) SPTLoginWelcomeViewLogger *logger; // @synthesize logger=_logger;
@property(nonatomic) __weak id <SPTLoginWelcomeViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)appleAuthorizationControllerWillLogIn;
- (void)appleAuthorizationControllerDidCompleteLoginWithError:(id)arg1;
- (id)appleAuthorizationControllerContext;
- (void)controller:(id)arg1 didCompleteFacebookLoginWithError:(id)arg2;
- (void)loginWithApple;
- (_Bool)isAppleSignInCustomStyleEnabled;
- (_Bool)isAppleSignInSystemStyleEnabled;
- (void)showSavedCredentialsDialog;
- (id)welcomeTitle;
- (void)logoutForgetUser:(_Bool)arg1;
- (void)cleanStickyCredentialsData;
- (void)navigateToLogin;
- (void)loginWithFacebook;
- (void)presentSignupStepOneViewController;
- (id)appleLogoIcon;
- (id)facebookLogoIcon;
- (id)facebookLogoIconWhite;
- (id)appleButtonText;
- (id)facebookButtonText;
- (id)signupButtonText;
- (id)loginButtonText;
- (id)spotifyLogo:(struct CGSize)arg1;
- (id)initWithLoginStateController:(id)arg1 logger:(id)arg2 facebookAuthController:(id)arg3 appleAuthController:(id)arg4 dialogController:(id)arg5 flowController:(id)arg6 databaseManager:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

