//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class SPTLyricsContentLayerContext, SPTLyricsV2GLUETheme, SPTLyricsV2LyricsViewController, SPTNowPlayingCoverArtImageView, SPTPlayerTrack;

@interface SPTLyricsContentLayerViewController : UIViewController
{
    SPTLyricsV2GLUETheme *_theme;
    SPTLyricsContentLayerContext *_context;
    SPTLyricsV2LyricsViewController *_lyricsViewController;
    SPTNowPlayingCoverArtImageView *_imageView;
    SPTPlayerTrack *_track;
}

@property(retain, nonatomic) SPTPlayerTrack *track; // @synthesize track=_track;
@property(readonly, nonatomic) SPTNowPlayingCoverArtImageView *imageView; // @synthesize imageView=_imageView;
@property(readonly, nonatomic) SPTLyricsV2LyricsViewController *lyricsViewController; // @synthesize lyricsViewController=_lyricsViewController;
@property(readonly, nonatomic) SPTLyricsContentLayerContext *context; // @synthesize context=_context;
@property(readonly, nonatomic) SPTLyricsV2GLUETheme *theme; // @synthesize theme=_theme;
- (void).cxx_destruct;
- (void)animateWithAnimations:(CDUnknownBlockType)arg1;
- (void)configureWithTrack:(id)arg1;
- (void)setupUI;
- (void)viewDidLoad;
- (id)initWithTheme:(id)arg1 context:(id)arg2;

@end

