//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface SPTLoginActionButtonManager : NSObject
{
    NSMutableArray *_actionButtons;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSMutableArray *actionButtons; // @synthesize actionButtons=_actionButtons;
- (void)applyStyle:(id)arg1;
- (void)addButton:(id)arg1 tag:(unsigned long long)arg2 toView:(id)arg3;
- (void)addButtons:(id)arg1 toView:(id)arg2;
- (id)init;

@end

