//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTFeatureFlagSignalObserver-Protocol.h"
#import "SPTLyricsV2TestManager-Protocol.h"

@class NSString;
@protocol SPTFeatureFlagFactory, SPTFeatureFlagSignal;

@interface SPTLyricsV2TestManagerImplementation : NSObject <SPTFeatureFlagSignalObserver, SPTLyricsV2TestManager>
{
    id <SPTFeatureFlagFactory> _featureFlagFactory;
    id <SPTFeatureFlagSignal> _lyricsV2FlagSignal;
    long long _lyricsV2FlagState;
    id <SPTFeatureFlagSignal> _vocalRemovalFlagSignal;
    long long _vocalRemovalFlagState;
    id <SPTFeatureFlagSignal> _syllableSyncFlagSignal;
    long long _syllableSyncFlagState;
    id <SPTFeatureFlagSignal> _lyricsNPBLabelSignal;
    long long _lyricsNPBLabelFlagState;
    id <SPTFeatureFlagSignal> _lyricsContentLayerSignal;
    long long _lyricsContentLayerFlagState;
}

@property(nonatomic) long long lyricsContentLayerFlagState; // @synthesize lyricsContentLayerFlagState=_lyricsContentLayerFlagState;
@property(retain, nonatomic) id <SPTFeatureFlagSignal> lyricsContentLayerSignal; // @synthesize lyricsContentLayerSignal=_lyricsContentLayerSignal;
@property(nonatomic) long long lyricsNPBLabelFlagState; // @synthesize lyricsNPBLabelFlagState=_lyricsNPBLabelFlagState;
@property(retain, nonatomic) id <SPTFeatureFlagSignal> lyricsNPBLabelSignal; // @synthesize lyricsNPBLabelSignal=_lyricsNPBLabelSignal;
@property(nonatomic) long long syllableSyncFlagState; // @synthesize syllableSyncFlagState=_syllableSyncFlagState;
@property(retain, nonatomic) id <SPTFeatureFlagSignal> syllableSyncFlagSignal; // @synthesize syllableSyncFlagSignal=_syllableSyncFlagSignal;
@property(nonatomic) long long vocalRemovalFlagState; // @synthesize vocalRemovalFlagState=_vocalRemovalFlagState;
@property(retain, nonatomic) id <SPTFeatureFlagSignal> vocalRemovalFlagSignal; // @synthesize vocalRemovalFlagSignal=_vocalRemovalFlagSignal;
@property(nonatomic) long long lyricsV2FlagState; // @synthesize lyricsV2FlagState=_lyricsV2FlagState;
@property(retain, nonatomic) id <SPTFeatureFlagSignal> lyricsV2FlagSignal; // @synthesize lyricsV2FlagSignal=_lyricsV2FlagSignal;
@property(readonly, nonatomic) id <SPTFeatureFlagFactory> featureFlagFactory; // @synthesize featureFlagFactory=_featureFlagFactory;
- (void).cxx_destruct;
- (_Bool)isContentLayerLyricsEnabled;
- (_Bool)isNowPlayingBarLyricsLabelEnabled;
- (_Bool)isSyllableSyncEnabled;
- (_Bool)isVocalRemovalEnabled;
- (_Bool)isFeatureEnabled;
- (void)featureFlagSignal:(id)arg1 hasAssumedState:(long long)arg2;
- (void)setupSyllableSyncFlags;
- (void)setupVocalRemovalFlags;
- (void)setupLyricsInNPVContentLayer;
- (void)setupLyricsNowPlayingBarLabel;
- (void)setupLyricsV2Flags;
- (void)setupFlags;
- (void)dealloc;
- (id)initWithFeatureFlagFactory:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

