//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SPTDynamicSignupFlowController;

@interface SPTLoginMethodLedStartScreenViewModel : NSObject
{
    SPTDynamicSignupFlowController *_flowController;
}

@property(readonly, nonatomic) SPTDynamicSignupFlowController *flowController; // @synthesize flowController=_flowController;
- (void).cxx_destruct;
- (void)userClickedSignup;
- (void)userClickedLogin;
- (id)buttonContainerHeadingText;
- (id)signupButtonText;
- (id)loginButtonText;
- (id)initWithFlowController:(id)arg1;

@end

