//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPTLoginTraitAwareViewController.h"

#import "SPTLoginViewControllerProtocol-Protocol.h"
#import "SPTLoginWelcomeViewModelDelegate-Protocol.h"
#import "SPTNavigationControllerNavigationBarState-Protocol.h"
#import "SPTPageController-Protocol.h"

@class NSError, NSString, NSURL, SPTLoginTheme, SPTLoginWelcomeView, SPTLoginWelcomeViewModel, SPTProgressView;
@protocol SPTPageContainer;

@interface SPTLoginWelcomeViewController : SPTLoginTraitAwareViewController <SPTNavigationControllerNavigationBarState, SPTLoginWelcomeViewModelDelegate, SPTPageController, SPTLoginViewControllerProtocol>
{
    _Bool performLogout;
    _Bool forgetUserAfterLogout;
    _Bool _reversePager;
    NSError *error;
    SPTLoginWelcomeViewModel *_viewModel;
    SPTLoginTheme *_theme;
    SPTProgressView *_progressIndicator;
}

@property(nonatomic) _Bool reversePager; // @synthesize reversePager=_reversePager;
@property(retain, nonatomic) SPTProgressView *progressIndicator; // @synthesize progressIndicator=_progressIndicator;
@property(readonly, nonatomic) SPTLoginTheme *theme; // @synthesize theme=_theme;
@property(readonly, nonatomic) SPTLoginWelcomeViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(copy, nonatomic) NSError *error; // @synthesize error;
@property(nonatomic) _Bool forgetUserAfterLogout; // @synthesize forgetUserAfterLogout;
@property(nonatomic) _Bool performLogout; // @synthesize performLogout;
- (void).cxx_destruct;
- (void)hideProgressIndicator;
- (void)showProgressIndicator;
- (unsigned long long)preferredNavigationBarState;
@property(readonly, nonatomic, getter=spt_pageIdentifier) NSString *pageIdentifier;
@property(readonly, nonatomic, getter=spt_pageURI) NSURL *pageURI;
- (void)viewModelDidFinishLogin:(id)arg1;
- (void)viewModelDidStartLogin:(id)arg1;
- (id)contextViewForWithModel:(id)arg1;
- (void)didCompleteFacebookLoginWithError:(id)arg1;
- (void)appleButtonTapped:(id)arg1;
- (void)signupButtonTapped:(id)arg1;
- (void)continueWithEmailButtonTapped:(id)arg1;
- (void)loginButtonTapped:(id)arg1;
- (void)facebookButtonTapped:(id)arg1;
- (void)configureButtonLayout;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithViewModel:(id)arg1 theme:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=spt_pageContainer) id <SPTPageContainer> pageContainer;
@property(readonly) Class superclass;
@property(retain, nonatomic) SPTLoginWelcomeView *view; // @dynamic view;

@end

