//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GLUEThemeBase.h"

@interface SPTLoginTheme : GLUEThemeBase
{
}

- (id)delayedSignupBannerStyle;
- (id)popupContainerViewStyle;
- (id)inputFormViewStyle:(_Bool)arg1;
- (id)delayedSignupTermsAndConditionsTextViewStyle;
- (id)termsAndConditionsTextViewStyle;
- (float)adjustTopInsetsFromCurrent:(float)arg1;
- (id)login_inputFieldDisclosureLabelStyle;
- (id)login_inputFieldHeadingLabelStyle:(_Bool)arg1;
- (id)login_titleHeadingLabelStyle;
- (id)login_backgroundColor;
- (id)formTextFieldStyle:(_Bool)arg1;
- (id)delayedSignup_signupButtonStyle;
- (id)delayedSignup_loginButtonStyle;
- (id)login_facebookButtonStyle;
- (id)login_whitePrimaryActionButtonStyle;
- (id)login_blackOutlinePrimaryActionButtonStyle;
- (id)login_whiteOutlinePrimaryActionButtonStyle;
- (id)delayedSignupYourLibraryDialogStyle;
- (id)delayedSignupShutDownDialogStyle;
- (id)delayedSignupWelcomeDialogStyle;
- (void)login_applySlideUpDefaultViewStyleToStyle:(id)arg1;
- (id)slideUpDialogDefaultViewStyle;
- (id)autosendLinkDialogViewStyle;
- (id)continueWithEmailViewStyle;
- (id)continueWithWelcomeViewStyle;
- (id)welcomeViewStyleForIPad:(_Bool)arg1;
- (id)magicLinkDoRequestViewStyle:(_Bool)arg1;
- (id)magicLinkSentConfirmationViewStyle:(_Bool)arg1;
- (id)singleInputFieldBaseViewStyle:(_Bool)arg1;
- (id)setNewPasswordViewStyle:(_Bool)arg1;
- (id)singleInputFieldSignupViewStyle:(_Bool)arg1;
- (id)facebookConfirmationViewStyle;
- (id)signupViewStyle:(_Bool)arg1;
- (id)loginViewStyle:(_Bool)arg1;

@end

