//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPTLoginTestManager.h"

@interface SPTLoginAppleSignInTestManager : SPTLoginTestManager
{
}

@property(readonly, nonatomic, getter=isAppleAccountLinkingDisabled) _Bool appleAccountLinkingDisabled;
@property(readonly, nonatomic, getter=isAppleSignUpDisabled) _Bool appleSignUpDisabled;
@property(readonly, nonatomic, getter=isAppleSignInCustomButtonEnabled) _Bool appleSignInCustomDesignEnabled;
@property(readonly, nonatomic, getter=isAppleSignInSystemButtonEnabled) _Bool appleSignInEnabled;

@end

