//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol SPTNowPlayingTabViewModelDelegate;

@interface SPTNowPlayingTabViewModel : NSObject
{
    NSString *_canvasTabTitle;
    NSString *_albumArtTabTitle;
    NSString *_lyricsTabTitle;
    id <SPTNowPlayingTabViewModelDelegate> _delegate;
}

@property(nonatomic) __weak id <SPTNowPlayingTabViewModelDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSString *lyricsTabTitle; // @synthesize lyricsTabTitle=_lyricsTabTitle;
@property(readonly, nonatomic) NSString *albumArtTabTitle; // @synthesize albumArtTabTitle=_albumArtTabTitle;
@property(readonly, nonatomic) NSString *canvasTabTitle; // @synthesize canvasTabTitle=_canvasTabTitle;
- (void).cxx_destruct;
- (void)didTapLyricsTab;
- (void)didTapAlbumArtTab;
- (void)didTapCanvasTab;
- (id)init;

@end

