//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class SPTNowPlayingModel, SPTNowPlayingPlaylistSteeringButton;

@interface SPTNowPlayingPlaylistSteeringButtonViewController : UIViewController
{
    SPTNowPlayingModel *_model;
    unsigned long long _steeringDirection;
    SPTNowPlayingPlaylistSteeringButton *_button;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SPTNowPlayingPlaylistSteeringButton *button; // @synthesize button=_button;
@property(nonatomic) unsigned long long steeringDirection; // @synthesize steeringDirection=_steeringDirection;
@property(retain, nonatomic) SPTNowPlayingModel *model; // @synthesize model=_model;
- (void)handleTouchUpInside:(id)arg1;
- (void)loadView;
- (id)initSteerDownWithModel:(id)arg1;
- (id)initSteerUpWithModel:(id)arg1;
- (id)initWithModel:(id)arg1 steeringDirection:(unsigned long long)arg2;

@end

