//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTPlayerObserver-Protocol.h"

@class NSString, SPTNowPlayingModel, SPTNowPlayingRemoteControlEventControllerManager, SPTPlayerState;
@protocol SPTAdsManager, SPTNowPlayingAuxiliaryActionsHandler, SPTNowPlayingRemoteControlPolicy, SPTNowPlayingRemoteControlPolicyRegistry, SPTNowPlayingTestManager, SPTPlayer;

@interface SPTNowPlayingRemoteControlPolicyResolver : NSObject <SPTPlayerObserver>
{
    id <SPTNowPlayingRemoteControlPolicy> _remoteControlPolicy;
    id <SPTNowPlayingRemoteControlPolicyRegistry> _remoteControlPolicyRegistry;
    id <SPTNowPlayingTestManager> _testManager;
    SPTNowPlayingRemoteControlEventControllerManager *_remoteControlManager;
    id <SPTAdsManager> _adsManager;
    SPTNowPlayingModel *_model;
    id <SPTPlayer> _player;
    id <SPTNowPlayingAuxiliaryActionsHandler> _auxiliaryActionsHandler;
    SPTPlayerState *_playerState;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SPTPlayerState *playerState; // @synthesize playerState=_playerState;
@property(readonly, nonatomic) id <SPTNowPlayingAuxiliaryActionsHandler> auxiliaryActionsHandler; // @synthesize auxiliaryActionsHandler=_auxiliaryActionsHandler;
@property(readonly, nonatomic) id <SPTPlayer> player; // @synthesize player=_player;
@property(readonly, nonatomic) SPTNowPlayingModel *model; // @synthesize model=_model;
@property(readonly, nonatomic) id <SPTAdsManager> adsManager; // @synthesize adsManager=_adsManager;
@property(readonly, nonatomic) SPTNowPlayingRemoteControlEventControllerManager *remoteControlManager; // @synthesize remoteControlManager=_remoteControlManager;
@property(readonly, nonatomic) id <SPTNowPlayingTestManager> testManager; // @synthesize testManager=_testManager;
@property(readonly, nonatomic) id <SPTNowPlayingRemoteControlPolicyRegistry> remoteControlPolicyRegistry; // @synthesize remoteControlPolicyRegistry=_remoteControlPolicyRegistry;
@property(retain, nonatomic) id <SPTNowPlayingRemoteControlPolicy> remoteControlPolicy; // @synthesize remoteControlPolicy=_remoteControlPolicy;
- (void)player:(id)arg1 stateDidChange:(id)arg2;
- (void)resolveRemoteControlPolicy;
- (id)initWithPlayer:(id)arg1 model:(id)arg2 remoteControlManager:(id)arg3 adsManager:(id)arg4 testManager:(id)arg5 remoteControlPolicyRegistry:(id)arg6 auxiliaryActionsHandler:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

