//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SPTNowPlayingLyricsButtonViewDelegate-Protocol.h"
#import "SPTNowPlayingModelObserver-Protocol.h"

@class NSString, SPTNowPlayingLogger, SPTNowPlayingLyricsButtonView, SPTNowPlayingModel;
@protocol SPTNowPlayingContentLayerResolver, SPTNowPlayingLyricsButtonViewControllerDelegate, SPTNowPlayingTestManager, SPTSnackbarConditionalPresenter;

@interface SPTNowPlayingLyricsButtonViewController : UIViewController <SPTNowPlayingLyricsButtonViewDelegate, SPTNowPlayingModelObserver>
{
    id <SPTNowPlayingLyricsButtonViewControllerDelegate> _delegate;
    SPTNowPlayingLyricsButtonView *_lyricsView;
    id <SPTSnackbarConditionalPresenter> _snackbarPresenter;
    id <SPTNowPlayingContentLayerResolver> _contentLayerResolver;
    id <SPTNowPlayingTestManager> _testManager;
    SPTNowPlayingLogger *_nowPlayingLogger;
    SPTNowPlayingModel *_model;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) SPTNowPlayingModel *model; // @synthesize model=_model;
@property(readonly, nonatomic) SPTNowPlayingLogger *nowPlayingLogger; // @synthesize nowPlayingLogger=_nowPlayingLogger;
@property(readonly, nonatomic) id <SPTNowPlayingTestManager> testManager; // @synthesize testManager=_testManager;
@property(readonly, nonatomic) id <SPTNowPlayingContentLayerResolver> contentLayerResolver; // @synthesize contentLayerResolver=_contentLayerResolver;
@property(readonly, nonatomic) id <SPTSnackbarConditionalPresenter> snackbarPresenter; // @synthesize snackbarPresenter=_snackbarPresenter;
@property(retain, nonatomic) SPTNowPlayingLyricsButtonView *lyricsView; // @synthesize lyricsView=_lyricsView;
@property(nonatomic) __weak id <SPTNowPlayingLyricsButtonViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)presentLyricsUpsellPopup;
- (void)toggleContentLayerLyricsView;
- (void)didTapLyricsView;
- (void)updateViewIfNeeded;
- (void)nowPlayingModel:(id)arg1 didMoveToRelativeTrack:(id)arg2;
- (void)nowPlayingModelDidUpdateMetadata:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (id)initWithTestManager:(id)arg1 contentLayerResolver:(id)arg2 nowPlayingLogger:(id)arg3 snackbarPresenter:(id)arg4 nowPlayingModel:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

