//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SPTNowPlayingContainedViewController-Protocol.h"

@class NSString, SPTTheme;
@protocol SPTNowPlayingContainingViewController;

@interface SPTNowPlayingHeadUnitViewController : UIViewController <SPTNowPlayingContainedViewController>
{
    UIViewController *_playPauseViewController;
    UIViewController *_leftSecondaryViewController;
    UIViewController *_rightSecondaryViewController;
    UIViewController *_leftTertiaryViewController;
    UIViewController *_rightTertiaryViewController;
    SPTTheme *_theme;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) SPTTheme *theme; // @synthesize theme=_theme;
@property(retain, nonatomic) UIViewController *rightTertiaryViewController; // @synthesize rightTertiaryViewController=_rightTertiaryViewController;
@property(retain, nonatomic) UIViewController *leftTertiaryViewController; // @synthesize leftTertiaryViewController=_leftTertiaryViewController;
@property(retain, nonatomic) UIViewController *rightSecondaryViewController; // @synthesize rightSecondaryViewController=_rightSecondaryViewController;
@property(retain, nonatomic) UIViewController *leftSecondaryViewController; // @synthesize leftSecondaryViewController=_leftSecondaryViewController;
@property(retain, nonatomic) UIViewController *playPauseViewController; // @synthesize playPauseViewController=_playPauseViewController;
- (struct CGSize)preferredContentSizeForContainerSize:(struct CGSize)arg1;
- (double)viewControllerPriority;
- (unsigned long long)leadingEdge;
- (void)setupConstraints;
- (void)addSubViewController:(id)arg1;
- (void)viewDidLoad;
- (id)initWithTheme:(id)arg1 playPauseViewController:(id)arg2 leftSecondaryViewController:(id)arg3 rightSecondaryViewController:(id)arg4 leftTertiaryViewController:(id)arg5 rightTertiaryViewController:(id)arg6;

// Remaining properties
@property(nonatomic) __weak UIViewController<SPTNowPlayingContainingViewController> *container;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

