//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTNowPlayingBarViewControllerObserver-Protocol.h"
#import "SPTNowPlayingStateObservable-Protocol.h"
#import "SPTNowPlayingTrackMetadataQueueObserver-Protocol.h"

@class NSString, SPTNowPlayingTrackMetadataQueue, SPTObserverManager, SPTStatefulPlayer, UIViewController;
@protocol SPTNowPlayingBarViewControllerObservable;

@interface SPTNowPlayingStateProxy : NSObject <SPTNowPlayingTrackMetadataQueueObserver, SPTNowPlayingBarViewControllerObserver, SPTNowPlayingStateObservable>
{
    SPTStatefulPlayer *_statefulPlayer;
    SPTNowPlayingTrackMetadataQueue *_trackMetadataQueue;
    UIViewController<SPTNowPlayingBarViewControllerObservable> *_barViewController;
    SPTObserverManager *_observerManager;
}

@property(retain, nonatomic) SPTObserverManager *observerManager; // @synthesize observerManager=_observerManager;
@property(nonatomic) __weak UIViewController<SPTNowPlayingBarViewControllerObservable> *barViewController; // @synthesize barViewController=_barViewController;
@property(readonly, nonatomic) SPTNowPlayingTrackMetadataQueue *trackMetadataQueue; // @synthesize trackMetadataQueue=_trackMetadataQueue;
@property(retain, nonatomic) SPTStatefulPlayer *statefulPlayer; // @synthesize statefulPlayer=_statefulPlayer;
- (void).cxx_destruct;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)nowPlayingBarViewControllerWillDisappear:(id)arg1;
- (void)nowPlayingBarViewControllerDidAppear:(id)arg1;
- (void)trackMetadataQueueWillSkipToNextTrack:(id)arg1;
- (id)initWithStatefulPlayer:(id)arg1 trackMetadataQueue:(id)arg2 barViewController:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

