//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class SPTEncoreLabel, UIStackView;

@interface SPTPremiumDestinationUIBenefitsChartHeaderView : UIView
{
    SPTEncoreLabel *_titleLabel;
    UIStackView *_stackView;
}

+ (double)maxColumnWidthForTitles:(id)arg1 style:(id)arg2;
+ (struct CGSize)sizeForContainerViewSize:(struct CGSize)arg1 style:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) UIStackView *stackView; // @synthesize stackView=_stackView;
@property(retain, nonatomic) SPTEncoreLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (id)viewsForColumnTitles:(id)arg1 style:(id)arg2;
- (void)setupConstraintsWithStyle:(id)arg1;
- (void)setupViewsWithStyle:(id)arg1 title:(id)arg2 columnTitles:(id)arg3;
- (id)initWithStyle:(id)arg1 title:(id)arg2 columnTitles:(id)arg3;

@end

