//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GLUEStatefulView.h"

@class GLUEImageView, GLUETrackAccessoryLabel, NSURL, SPTPodcastTrailerAccessoryLabel, SPTPodcastTrailerSectionCircularProgressView, SPTTheme, UIControl, UIImageView, UILabel, UIStackView, UIView;
@protocol GLUEImageLoader;

@interface SPTPodcastTrailerSectionContentView : GLUEStatefulView
{
    id <GLUEImageLoader> _imageLoader;
    SPTTheme *_catTheme;
    NSURL *_imageURL;
    GLUEImageView *_imageView;
    UIImageView *_playIconImageView;
    UIView *_backgroundDarkeningView;
    SPTPodcastTrailerSectionCircularProgressView *_progressView;
    UILabel *_titleLabel;
    SPTPodcastTrailerAccessoryLabel *_trailerLabel;
    UILabel *_durationLabel;
    UIStackView *_metadataContainerStackView;
    UIStackView *_metadataSubContainerStackView;
    UIControl *_playControl;
    GLUETrackAccessoryLabel *_explicitLabel;
}

@property(retain, nonatomic) GLUETrackAccessoryLabel *explicitLabel; // @synthesize explicitLabel=_explicitLabel;
@property(retain, nonatomic) UIControl *playControl; // @synthesize playControl=_playControl;
@property(retain, nonatomic) UIStackView *metadataSubContainerStackView; // @synthesize metadataSubContainerStackView=_metadataSubContainerStackView;
@property(retain, nonatomic) UIStackView *metadataContainerStackView; // @synthesize metadataContainerStackView=_metadataContainerStackView;
@property(retain, nonatomic) UILabel *durationLabel; // @synthesize durationLabel=_durationLabel;
@property(retain, nonatomic) SPTPodcastTrailerAccessoryLabel *trailerLabel; // @synthesize trailerLabel=_trailerLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) SPTPodcastTrailerSectionCircularProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIView *backgroundDarkeningView; // @synthesize backgroundDarkeningView=_backgroundDarkeningView;
@property(retain, nonatomic) UIImageView *playIconImageView; // @synthesize playIconImageView=_playIconImageView;
@property(retain, nonatomic) GLUEImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(retain, nonatomic) SPTTheme *catTheme; // @synthesize catTheme=_catTheme;
@property(retain, nonatomic) id <GLUEImageLoader> imageLoader; // @synthesize imageLoader=_imageLoader;
- (void).cxx_destruct;
- (id)explicitLabelStyle;
- (id)providePlaceholderImage;
- (void)updateProgressVisibility:(_Bool)arg1;
- (id)defineDurationTextColor:(_Bool)arg1;
- (id)defineTitleColor:(_Bool)arg1;
- (void)updateWithViewModel:(id)arg1;
- (void)configureLayout;
- (void)configureAppearance;
- (id)initWithTheme:(id)arg1;

@end

