//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTPageLoadable-Protocol.h"
#import "SPTPodcastEpisodeViewModelDelegate-Protocol.h"

@class NSString, SPTPodcastEpisodeViewModel;
@protocol SPTPageLoadStateHandler;

@interface SPTPodcastEpisodePageLoadable : NSObject <SPTPodcastEpisodeViewModelDelegate, SPTPageLoadable>
{
    SPTPodcastEpisodeViewModel *_episodeViewModel;
    id <SPTPageLoadStateHandler> _handler;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id <SPTPageLoadStateHandler> handler; // @synthesize handler=_handler;
@property(retain, nonatomic) SPTPodcastEpisodeViewModel *episodeViewModel; // @synthesize episodeViewModel=_episodeViewModel;
- (void)viewModelUpdatedPlaybackState:(id)arg1;
- (void)viewModel:(id)arg1 didUpdateWithError:(id)arg2;
- (void)cancel;
- (void)loadWithResultHandler:(id)arg1;
- (id)initWithEpisodeViewModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

