//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface SPTPodcastEntitiesModel : NSObject
{
    NSArray *_entities;
    NSString *_uri;
}

@property(readonly, copy, nonatomic) NSString *uri; // @synthesize uri=_uri;
@property(readonly, nonatomic) NSArray *entities; // @synthesize entities=_entities;
- (void).cxx_destruct;
- (id)mosaicImageURL;
- (id)initWithDictionary:(id)arg1;

@end

