//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTFreeTierPlaylistPlayViewModel-Protocol.h"

@class NSString, NSURL, SPTPlayOrigin;
@protocol SPTFreeTierPlaylistPlayLogger, SPTFreeTierPlaylistPlayModel, SPTFreeTierPlaylistPlayViewModel, SPTPlayer;

@interface SPTPodcastMixOnDemandPlaylistPlayViewModel : NSObject <SPTFreeTierPlaylistPlayViewModel>
{
    SPTPlayOrigin *_playOrigin;
    id <SPTFreeTierPlaylistPlayModel> _playModel;
    id <SPTFreeTierPlaylistPlayViewModel> _playViewModel;
    id <SPTFreeTierPlaylistPlayLogger> _playLogger;
    id <SPTPlayer> _player;
    NSURL *_playlistURI;
}

@property(readonly, nonatomic) NSURL *playlistURI; // @synthesize playlistURI=_playlistURI;
@property(readonly, nonatomic) id <SPTPlayer> player; // @synthesize player=_player;
@property(readonly, nonatomic) id <SPTFreeTierPlaylistPlayLogger> playLogger; // @synthesize playLogger=_playLogger;
@property(readonly, nonatomic) id <SPTFreeTierPlaylistPlayViewModel> playViewModel; // @synthesize playViewModel=_playViewModel;
@property(readonly, nonatomic) id <SPTFreeTierPlaylistPlayModel> playModel; // @synthesize playModel=_playModel;
@property(readonly, nonatomic) SPTPlayOrigin *playOrigin; // @synthesize playOrigin=_playOrigin;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isPlayButtonPausingPlay) _Bool playButtonPausingPlay;
@property(readonly, nonatomic) _Bool shouldShowPlayButton;
@property(readonly, nonatomic, getter=isPlaylistPlaying) _Bool playlistPlaying;
- (id)playOptions;
- (void)playTrackEntity:(id)arg1;
- (void)play;
- (_Bool)isPlayingCurrentContext;
@property(readonly, nonatomic, getter=isPlayButtonUsedForPlayback) _Bool playButtonUsedForPlayback;
- (id)initWithPlayViewModel:(id)arg1 playModel:(id)arg2 playOrigin:(id)arg3 playLogger:(id)arg4 player:(id)arg5 playlistURI:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

