//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTPremiumDestinationUIService-Protocol.h"

@class HUBComponentRegistry, NSString, SPTAllocationContext;
@protocol SPTGLUEService, SPTHugsFactory, SPTPremiumDestinationUIHubComponentFactory;

@interface SPTPremiumDestinationUIServiceImplementation : NSObject <SPTPremiumDestinationUIService>
{
    id <SPTGLUEService> _glueService;
    id <SPTHugsFactory> _hugsFactory;
    HUBComponentRegistry *_componentRegistry;
    id <SPTPremiumDestinationUIHubComponentFactory> _componentFactory;
}

+ (id)serviceIdentifier;
@property(retain, nonatomic) id <SPTPremiumDestinationUIHubComponentFactory> componentFactory; // @synthesize componentFactory=_componentFactory;
@property(retain, nonatomic) HUBComponentRegistry *componentRegistry; // @synthesize componentRegistry=_componentRegistry;
@property(nonatomic) __weak id <SPTHugsFactory> hugsFactory; // @synthesize hugsFactory=_hugsFactory;
@property(nonatomic) __weak id <SPTGLUEService> glueService; // @synthesize glueService=_glueService;
- (void).cxx_destruct;
- (id)providePremiumDestinationUIGLUETheme;
- (id)provideHubsComponentRegistry;
- (void)unload;
- (void)load;
- (void)configureWithServices:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

