//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SPTPodcastEpisodeFeaturedContentTrackListPreviewViewDelegate-Protocol.h"

@class GLUESectionHeaderView, NSString, SPTPodcastEntitiesModel, SPTPodcastEpisodeFeaturedContentDataLoader, SPTPodcastEpisodeFeaturedContentTrackListPreviewView;
@protocol GLUEImageLoader, SPTLinkDispatcher;

@interface SPTPodcastEpisodeFeaturedContentTrackListPreviewViewController : UIViewController <SPTPodcastEpisodeFeaturedContentTrackListPreviewViewDelegate>
{
    GLUESectionHeaderView *_sectionHeaderView;
    SPTPodcastEpisodeFeaturedContentTrackListPreviewView *_previewView;
    NSString *_episodeURIString;
    SPTPodcastEpisodeFeaturedContentDataLoader *_dataLoader;
    id <GLUEImageLoader> _imageLoader;
    id <SPTLinkDispatcher> _linkDispatcher;
    SPTPodcastEntitiesModel *_podcastEntitiesModel;
}

@property(retain, nonatomic) SPTPodcastEntitiesModel *podcastEntitiesModel; // @synthesize podcastEntitiesModel=_podcastEntitiesModel;
@property(readonly, nonatomic) id <SPTLinkDispatcher> linkDispatcher; // @synthesize linkDispatcher=_linkDispatcher;
@property(readonly, nonatomic) id <GLUEImageLoader> imageLoader; // @synthesize imageLoader=_imageLoader;
@property(readonly, nonatomic) SPTPodcastEpisodeFeaturedContentDataLoader *dataLoader; // @synthesize dataLoader=_dataLoader;
@property(readonly, copy, nonatomic) NSString *episodeURIString; // @synthesize episodeURIString=_episodeURIString;
@property(retain, nonatomic) SPTPodcastEpisodeFeaturedContentTrackListPreviewView *previewView; // @synthesize previewView=_previewView;
@property(retain, nonatomic) GLUESectionHeaderView *sectionHeaderView; // @synthesize sectionHeaderView=_sectionHeaderView;
- (void).cxx_destruct;
- (void)navigateToTimeline;
- (void)podcastEpisodeFeaturedContentTrackListPreviewViewDidSelect:(id)arg1;
- (void)setContentHidden:(_Bool)arg1;
- (void)handleFetchedModel:(id)arg1;
- (void)fetchPodcastInspectorModel;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithEpisodeURI:(id)arg1 podcastInspectorDataLoader:(id)arg2 imageLoader:(id)arg3 linkDispatcher:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

