//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTPageLoadable-Protocol.h"

@class NSURL;
@protocol SPTPodcastEntityDataLoader;

@interface SPTPodcastPageLoadable : NSObject <SPTPageLoadable>
{
    NSURL *_URI;
    id <SPTPodcastEntityDataLoader> _entityDataLoader;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <SPTPodcastEntityDataLoader> entityDataLoader; // @synthesize entityDataLoader=_entityDataLoader;
@property(readonly, nonatomic) NSURL *URI; // @synthesize URI=_URI;
- (void)loadWithResultHandler:(id)arg1;
- (void)cancel;
- (id)initWithPodcastURI:(id)arg1 dataLoader:(id)arg2;

@end

