//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPTPodcastUIBaseHeaderContentView.h"

#import "VISREFHeaderComponent-Protocol.h"

@class GLUELabel, NSLayoutConstraint, NSString, SPTEncoreLabel, SPTPodcastUIEditorialHeaderStyle, UIImage, UILayoutGuide, UIView, VISREFAlignedImageView, VISREFGradientView;
@protocol GLUETheme;

@interface SPTPodcastUIEditorialHeaderContentView : SPTPodcastUIBaseHeaderContentView <VISREFHeaderComponent>
{
    SPTEncoreLabel *_titleLabel;
    UIView *_actionRowView;
    id <GLUETheme> _theme;
    SPTPodcastUIEditorialHeaderStyle *_headerStyle;
    GLUELabel *_descriptionLabel;
    VISREFGradientView *_titleProtectionGradient;
    VISREFAlignedImageView *_alignedImageView;
    UILayoutGuide *_actionRowLayoutGuide;
    NSLayoutConstraint *_imageWidthConstraint;
    NSLayoutConstraint *_noDescriptionActionRowTopConstraint;
    NSLayoutConstraint *_descriptionActionRowTopConstraint;
    NSLayoutConstraint *_actionRowLeadingConstraint;
    NSLayoutConstraint *_descriptionHeightConstraint;
    NSLayoutConstraint *_actionRowHeightConstraint;
    double _lastProgress;
    double _lastWidth;
    CDUnknownBlockType _topicTappedAtIndexBlock;
    NSLayoutConstraint *_imageAspectConstraint;
    VISREFGradientView *_statusBarProtectionGradient;
    CDStruct_5a28e70a _imageAlphaProgressRange;
    CDStruct_5a28e70a _statusBarProtectionProgressRange;
    CDStruct_5a28e70a _titleLabelAlphaProgressRange;
    CDStruct_5a28e70a _titleProtectionProgressRange;
}

@property(nonatomic) CDStruct_5a28e70a titleProtectionProgressRange; // @synthesize titleProtectionProgressRange=_titleProtectionProgressRange;
@property(nonatomic) CDStruct_5a28e70a titleLabelAlphaProgressRange; // @synthesize titleLabelAlphaProgressRange=_titleLabelAlphaProgressRange;
@property(nonatomic) CDStruct_5a28e70a statusBarProtectionProgressRange; // @synthesize statusBarProtectionProgressRange=_statusBarProtectionProgressRange;
@property(nonatomic) CDStruct_5a28e70a imageAlphaProgressRange; // @synthesize imageAlphaProgressRange=_imageAlphaProgressRange;
@property(retain, nonatomic) VISREFGradientView *statusBarProtectionGradient; // @synthesize statusBarProtectionGradient=_statusBarProtectionGradient;
@property(retain, nonatomic) NSLayoutConstraint *imageAspectConstraint; // @synthesize imageAspectConstraint=_imageAspectConstraint;
@property(copy, nonatomic) CDUnknownBlockType topicTappedAtIndexBlock; // @synthesize topicTappedAtIndexBlock=_topicTappedAtIndexBlock;
@property(nonatomic) double lastWidth; // @synthesize lastWidth=_lastWidth;
@property(nonatomic) double lastProgress; // @synthesize lastProgress=_lastProgress;
@property(retain, nonatomic) NSLayoutConstraint *actionRowHeightConstraint; // @synthesize actionRowHeightConstraint=_actionRowHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *descriptionHeightConstraint; // @synthesize descriptionHeightConstraint=_descriptionHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *actionRowLeadingConstraint; // @synthesize actionRowLeadingConstraint=_actionRowLeadingConstraint;
@property(retain, nonatomic) NSLayoutConstraint *descriptionActionRowTopConstraint; // @synthesize descriptionActionRowTopConstraint=_descriptionActionRowTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *noDescriptionActionRowTopConstraint; // @synthesize noDescriptionActionRowTopConstraint=_noDescriptionActionRowTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *imageWidthConstraint; // @synthesize imageWidthConstraint=_imageWidthConstraint;
@property(retain, nonatomic) UILayoutGuide *actionRowLayoutGuide; // @synthesize actionRowLayoutGuide=_actionRowLayoutGuide;
@property(retain, nonatomic) VISREFAlignedImageView *alignedImageView; // @synthesize alignedImageView=_alignedImageView;
@property(retain, nonatomic) VISREFGradientView *titleProtectionGradient; // @synthesize titleProtectionGradient=_titleProtectionGradient;
@property(retain, nonatomic) GLUELabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(readonly, nonatomic) SPTPodcastUIEditorialHeaderStyle *headerStyle; // @synthesize headerStyle=_headerStyle;
@property(readonly, nonatomic) id <GLUETheme> theme; // @synthesize theme=_theme;
@property(retain, nonatomic) UIView *actionRowView; // @synthesize actionRowView=_actionRowView;
@property(retain, nonatomic) SPTEncoreLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)setAssociatedColor:(id)arg1;
- (void)updateDescriptionConstraint;
- (void)setDescriptionText:(id)arg1;
- (void)setTitleText:(id)arg1;
@property(retain, nonatomic) UIImage *image;
- (void)setImage:(id)arg1 animated:(_Bool)arg2;
- (void)headerViewDidRemountHeaderComponents:(id)arg1;
- (double)normalizeProgress:(double)arg1 minValue:(double)arg2 maxValue:(double)arg3;
- (void)fullHeaderViewNormalizedProgressUpdate:(double)arg1;
- (void)headerViewNormalizedProgressUpdate:(double)arg1;
- (void)layoutSubviews;
- (void)updateProgressPositions;
- (void)setupActionRowHeight;
- (void)setupLayout;
- (void)setup;
- (id)initWithTheme:(id)arg1 naturalHeight:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

