//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSData, NSPredicate, NSString;

@protocol SPTPodcastRequestData <NSObject>
@property(nonatomic, readonly) NSString *requestAction;
@property(nonatomic, readonly) NSArray *sortDescriptors;
@property(nonatomic, readonly) NSPredicate *filterPredicate;
@property(nonatomic, readonly) NSString *requestStringTemplate;

@optional
- (_Bool)isGrouped;
@property(nonatomic, readonly) NSData *requestBody;

// Remaining properties
@property(nonatomic, readonly) _Bool grouped;
@end

