//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray;
@protocol SPTExplicitContentAccessManager;

@interface SPTPodcastViewSectionConfiguration : NSObject
{
    NSArray *_viewSections;
    NSMutableArray *_viewSectionContainers;
    id <SPTExplicitContentAccessManager> _explicitContentAccessManager;
}

@property(nonatomic) __weak id <SPTExplicitContentAccessManager> explicitContentAccessManager; // @synthesize explicitContentAccessManager=_explicitContentAccessManager;
@property(retain, nonatomic) NSMutableArray *viewSectionContainers; // @synthesize viewSectionContainers=_viewSectionContainers;
@property(copy, nonatomic) NSArray *viewSections; // @synthesize viewSections=_viewSections;
- (void).cxx_destruct;
- (id)instanceForSectionIdentifier:(long long)arg1;
- (void)enableSection:(long long)arg1;
- (void)createViewModelSectionsFromContainers:(id)arg1 podcastPlayer:(id)arg2 cellConfigurator:(id)arg3 cellActionHandler:(id)arg4 collectionLogger:(id)arg5 podcastLogger:(id)arg6 podcastTestManager:(id)arg7 podcastURL:(id)arg8 sortingService:(id)arg9 explicitContentAccessManager:(id)arg10;
- (id)initWithViewContainers:(id)arg1 podcastPlayer:(id)arg2 cellConfigurator:(id)arg3 cellActionHandler:(id)arg4 collectionLogger:(id)arg5 podcastLogger:(id)arg6 podcastTestManager:(id)arg7 podcastURL:(id)arg8 sortingService:(id)arg9 explicitContentAccessManager:(id)arg10;

@end

