//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VISREFHeaderController-Protocol.h"

@class UIImage, UIView;
@protocol HUBComponentEventHandler, HUBComponentModel;

@protocol SPTPodcastUIEditorialHeaderController <VISREFHeaderController>
- (void)setNavigationBarHeight:(double)arg1;
- (void)configureWithModel:(id <HUBComponentModel>)arg1 eventHandler:(id <HUBComponentEventHandler>)arg2;
- (double)headerHeight;

@optional
- (void)addActionRowView:(UIView *)arg1;
- (void)setImage:(UIImage *)arg1;
@end

