//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP16SPTServiceSystem28SPTServiceInstanceInteractor_-Protocol.h"

@class NSString, SPTStartupTracer, _TtC16SPTServiceSystem35SPTDefaultServiceInstanceInteractor;
@protocol OS_os_log;

@interface SPTPerformanceMonitoringServiceInteractor : NSObject <_TtP16SPTServiceSystem28SPTServiceInstanceInteractor_>
{
    _TtC16SPTServiceSystem35SPTDefaultServiceInstanceInteractor *_defaultInteractor;
    SPTStartupTracer *_startupTracer;
    NSObject<OS_os_log> *_instrumentationLog;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSObject<OS_os_log> *instrumentationLog; // @synthesize instrumentationLog=_instrumentationLog;
@property(readonly, nonatomic) SPTStartupTracer *startupTracer; // @synthesize startupTracer=_startupTracer;
@property(readonly, nonatomic) _TtC16SPTServiceSystem35SPTDefaultServiceInstanceInteractor *defaultInteractor; // @synthesize defaultInteractor=_defaultInteractor;
- (void)notifyServiceThatIdleStateWasReached:(id)arg1 scope:(id)arg2;
- (void)notifyServiceThatInitialViewDidAppear:(id)arg1 scope:(id)arg2;
- (void)unloadService:(id)arg1 scope:(id)arg2;
- (void)loadService:(id)arg1 scope:(id)arg2;
- (void)configureService:(id)arg1 scope:(id)arg2 serviceProvider:(id)arg3;
- (id)instantiateServiceClass:(Class)arg1 scope:(id)arg2;
- (id)identifierForService:(id)arg1;
- (id)identifierForServiceClass:(Class)arg1;
- (id)allocationContextForIdentifier:(id)arg1;
- (id)initWithStartupTracer:(id)arg1 instrumentationLog:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

