//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SPTObserverManager;

@interface SPTPodcastFollowButtonPressedObserver : NSObject
{
    SPTObserverManager *_observer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SPTObserverManager *observer; // @synthesize observer=_observer;
- (void)notifyObservers:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)init;

@end

