//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSLayoutConstraint, SPTEncoreLabel, UIStackView;

@interface SPTPremiumDestinationUIBenefitsChartRow : UIView
{
    NSLayoutConstraint *_stackViewWidthConstraint;
    SPTEncoreLabel *_titleLabel;
    UIStackView *_stackView;
    UIView *_separatorView;
}

+ (struct CGSize)sizeForContainerViewSize:(struct CGSize)arg1 stackViewWidth:(double)arg2 chartItem:(id)arg3 style:(id)arg4;
- (void).cxx_destruct;
@property(retain, nonatomic) UIView *separatorView; // @synthesize separatorView=_separatorView;
@property(retain, nonatomic) UIStackView *stackView; // @synthesize stackView=_stackView;
@property(retain, nonatomic) SPTEncoreLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSLayoutConstraint *stackViewWidthConstraint; // @synthesize stackViewWidthConstraint=_stackViewWidthConstraint;
- (id)viewsForColumnItems:(id)arg1 withStyle:(id)arg2;
- (void)setupConstraintsWithStyle:(id)arg1;
- (void)setupViewsWithStyle:(id)arg1 chartItem:(id)arg2;
- (id)initWithStyle:(id)arg1 chartItem:(id)arg2;

@end

