//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "SPContentInsetViewController-Protocol.h"
#import "SPTPageController-Protocol.h"
#import "SPTPodcastEpisodeFeaturedContentPlayerPlayerDelegate-Protocol.h"

@class NSString, NSURL, SPTPodcastEntitiesModel, SPTPodcastEpisodeFeaturedContentContextMenuPresenter, SPTPodcastEpisodeFeaturedContentDataLoader, SPTPodcastEpisodeFeaturedContentPlayer;
@protocol GLUEImageLoader, SPTPageContainer;

@interface SPTPodcastEpisodeFeaturedContentTrackTimelineViewController : UITableViewController <SPContentInsetViewController, SPTPodcastEpisodeFeaturedContentPlayerPlayerDelegate, SPTPageController>
{
    _Bool _configureForEmbeddingInScrollView;
    NSString *_episodeURIString;
    SPTPodcastEpisodeFeaturedContentDataLoader *_dataLoader;
    id <GLUEImageLoader> _imageLoader;
    SPTPodcastEpisodeFeaturedContentContextMenuPresenter *_contextMenuPresenter;
    SPTPodcastEpisodeFeaturedContentPlayer *_featuredContentPlayer;
    SPTPodcastEntitiesModel *_podcastEntitiesModel;
}

@property(readonly, nonatomic, getter=shouldConfigureForEmbeddingInScrollView) _Bool configureForEmbeddingInScrollView; // @synthesize configureForEmbeddingInScrollView=_configureForEmbeddingInScrollView;
@property(retain, nonatomic) SPTPodcastEntitiesModel *podcastEntitiesModel; // @synthesize podcastEntitiesModel=_podcastEntitiesModel;
@property(readonly, nonatomic) SPTPodcastEpisodeFeaturedContentPlayer *featuredContentPlayer; // @synthesize featuredContentPlayer=_featuredContentPlayer;
@property(readonly, nonatomic) SPTPodcastEpisodeFeaturedContentContextMenuPresenter *contextMenuPresenter; // @synthesize contextMenuPresenter=_contextMenuPresenter;
@property(readonly, nonatomic) id <GLUEImageLoader> imageLoader; // @synthesize imageLoader=_imageLoader;
@property(readonly, nonatomic) SPTPodcastEpisodeFeaturedContentDataLoader *dataLoader; // @synthesize dataLoader=_dataLoader;
@property(readonly, copy, nonatomic) NSString *episodeURIString; // @synthesize episodeURIString=_episodeURIString;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=spt_pageURI) NSURL *pageURI;
@property(readonly, nonatomic, getter=spt_pageIdentifier) NSString *pageIdentifier;
- (void)playerDidStopPlayingEntity:(id)arg1;
- (void)playerDidUpdateWithEntityPlaying:(id)arg1;
- (void)sp_updateContentInsets;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)handleFetchedModel:(id)arg1;
- (void)fetchPodcastInspectorModel;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)setUpNavigationItem;
- (id)initWithEpisodeURI:(id)arg1 podcastInspectorDataLoader:(id)arg2 imageLoader:(id)arg3 contextMenuPresenter:(id)arg4 featuredContentPlayer:(id)arg5 configureForEmbeddingInScrollView:(_Bool)arg6;

// Remaining properties
@property(nonatomic) _Bool automaticallyAdjustsScrollViewInsets;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=spt_pageContainer) id <SPTPageContainer> pageContainer;
@property(readonly) Class superclass;

@end

