//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTFreeTierPlaylistAdditionalCallToAction-Protocol.h"

@class NSString, NSURL;
@protocol SPTLinkDispatcher;

@interface SPTPodcastMixCallToActionCustomize : NSObject <SPTFreeTierPlaylistAdditionalCallToAction>
{
    id <SPTLinkDispatcher> _linkDispatcher;
    NSURL *_targetURI;
}

@property(retain, nonatomic) NSURL *targetURI; // @synthesize targetURI=_targetURI;
@property(nonatomic) __weak id <SPTLinkDispatcher> linkDispatcher; // @synthesize linkDispatcher=_linkDispatcher;
- (void).cxx_destruct;
- (void)performAction:(id)arg1;
@property(readonly, nonatomic) _Bool enabled;
@property(readonly, copy, nonatomic) NSString *title;
- (id)initWithTargetURI:(id)arg1 linkDispatcher:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

