//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, NSURL, SPTPodcastGenericEntity;

@interface SPTPodcastEntity : NSObject
{
    NSURL *_uri;
    NSString *_title;
    NSString *_subtitle;
    NSURL *_imageUri;
    SPTPodcastGenericEntity *_album;
    NSArray *_artists;
    unsigned long long _startTime;
    unsigned long long _endTime;
}

@property(nonatomic) unsigned long long endTime; // @synthesize endTime=_endTime;
@property(nonatomic) unsigned long long startTime; // @synthesize startTime=_startTime;
@property(readonly, nonatomic) NSArray *artists; // @synthesize artists=_artists;
@property(readonly, nonatomic) SPTPodcastGenericEntity *album; // @synthesize album=_album;
@property(readonly, nonatomic) NSURL *imageUri; // @synthesize imageUri=_imageUri;
@property(readonly, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSURL *uri; // @synthesize uri=_uri;
- (void).cxx_destruct;
- (id)formattedTrackStartTime;
- (double)endTimeInterval;
- (double)startTimeInterval;
- (id)initWithDictionary:(id)arg1;

@end

