//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SpotifyApplicationRemoteControlDelegate, SpotifyApplicationRemoteControlObserver;

@protocol SPTSpotifyApplication <NSObject>
@property(nonatomic) __weak id <SpotifyApplicationRemoteControlDelegate> remoteControlDelegate;
- (void)removeRemoteControlObserver:(id <SpotifyApplicationRemoteControlObserver>)arg1;
- (void)addRemoteControlObserver:(id <SpotifyApplicationRemoteControlObserver>)arg1;
- (_Bool)handleRemoteControlEventOfSubtype:(long long)arg1;
@end

