//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTFeatureFlagSignalObserver-Protocol.h"
#import "SPTSnackbarTestManager-Protocol.h"

@class NSString;
@protocol SPTFeatureFlagFactory, SPTFeatureFlagSignal;

@interface SPTSnackbarTestManagerImplementation : NSObject <SPTFeatureFlagSignalObserver, SPTSnackbarTestManager>
{
    _Bool _snackbarRefreshEnabled;
    id <SPTFeatureFlagFactory> _featureFlagFactory;
    id <SPTFeatureFlagSignal> _snackbarRefreshEnabledSignal;
}

@property(nonatomic, getter=isSnackbarRefreshEnabled) _Bool snackbarRefreshEnabled; // @synthesize snackbarRefreshEnabled=_snackbarRefreshEnabled;
@property(retain, nonatomic) id <SPTFeatureFlagSignal> snackbarRefreshEnabledSignal; // @synthesize snackbarRefreshEnabledSignal=_snackbarRefreshEnabledSignal;
@property(readonly, nonatomic) id <SPTFeatureFlagFactory> featureFlagFactory; // @synthesize featureFlagFactory=_featureFlagFactory;
- (void).cxx_destruct;
- (void)setupSnackbarRefreshFlag;
- (void)featureFlagSignal:(id)arg1 hasAssumedState:(long long)arg2;
- (void)dealloc;
- (id)initWithFeatureFlagFactory:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

