//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTSharingSDKShareDialogPresenter-Protocol.h"

@class NSString, SPTShareFacebookDialogPresenter, UIViewController;

@interface SPTShareDialogPresenter : NSObject <SPTSharingSDKShareDialogPresenter>
{
    UIViewController *_contextViewController;
    SPTShareFacebookDialogPresenter *_facebookDialogPresenter;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) SPTShareFacebookDialogPresenter *facebookDialogPresenter; // @synthesize facebookDialogPresenter=_facebookDialogPresenter;
@property(readonly, nonatomic) __weak UIViewController *contextViewController; // @synthesize contextViewController=_contextViewController;
- (void)presentShareDialogForDestination:(unsigned long long)arg1 shareableData:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)initWithContextViewController:(id)arg1 facebookDialogPresenter:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

