//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SPTShadowPlaylistURIResolver;
@protocol SPTPlaylistRoute;

@protocol SPTShadowPlaylistURIResolverObserver <NSObject>
- (void)uriResolver:(SPTShadowPlaylistURIResolver *)arg1 didUpdateRoute:(id <SPTPlaylistRoute>)arg2;
- (void)uriResolver:(SPTShadowPlaylistURIResolver *)arg1 didCreateShadow:(id <SPTPlaylistRoute>)arg2;
@end

