//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary;
@protocol SPTLocalSettings, SPTPlaylistModel;

@interface SPTShadowPlaylistURIResolver : NSObject
{
    NSMutableDictionary *_shadowList;
    id <SPTPlaylistModel> _playlistModel;
    id <SPTLocalSettings> _localSettings;
}

@property(retain, nonatomic) id <SPTLocalSettings> localSettings; // @synthesize localSettings=_localSettings;
@property(retain, nonatomic) id <SPTPlaylistModel> playlistModel; // @synthesize playlistModel=_playlistModel;
@property(retain, nonatomic) NSMutableDictionary *shadowList; // @synthesize shadowList=_shadowList;
- (void).cxx_destruct;
- (void)clearPlaylist:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)resolveShadowPlaylistFor:(id)arg1 withCompletion:(CDUnknownBlockType)arg2 onError:(CDUnknownBlockType)arg3;
- (void)resolveWriteURIFor:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)resolveReadURIFor:(id)arg1;
- (_Bool)hasShadowFor:(id)arg1;
- (id)readUriFor:(id)arg1;
- (void)shadowPlaylistFor:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)createShadowPlaylistFor:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)shouldRouteUri:(id)arg1;
- (void)saveShadowPlaylist:(id)arg1 forShadowName:(id)arg2;
@property(readonly, nonatomic) NSDictionary *urisToRoute;
- (id)initWithLocalSettings:(id)arg1;

@end

