//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPTShadowPlaylistProxy.h"

@class NSString;

@interface SPTShadowPlaylistTrackViewModel : SPTShadowPlaylistProxy
{
    _Bool _isActive;
    NSString *_rowId;
}

@property(copy, nonatomic) NSString *rowId; // @synthesize rowId=_rowId;
@property(nonatomic) _Bool isActive; // @synthesize isActive=_isActive;
- (void).cxx_destruct;
- (_Bool)shadowsSelector:(SEL)arg1;

@end

