//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SPTSortingFilteringButtonsContainer, SPTSortingFilteringFilterRule;

@protocol SPTSortingFilteringButtonsContainerDelegate <NSObject>
- (void)sortingFilteringButtonsContainer:(id <SPTSortingFilteringButtonsContainer>)arg1 deselectedFilterRule:(id <SPTSortingFilteringFilterRule>)arg2;
- (void)sortingFilteringButtonsContainer:(id <SPTSortingFilteringButtonsContainer>)arg1 selectedFilterRule:(id <SPTSortingFilteringFilterRule>)arg2;
@end

