//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SPTSearchPlatformTestManager <NSObject>
@property(readonly, nonatomic, getter=isNewRecentsRowEnabled) _Bool newRecentsRowEnabled;
@property(readonly, nonatomic, getter=isLyricsRowDebuggingEnabled) _Bool lyricsRowDebuggingEnabled;
@property(readonly, nonatomic, getter=isTopicsEnabled) _Bool topicsEnabled;
@property(readonly, nonatomic, getter=areNewPodcastRowsEnabled) _Bool newPodcastRowsEnabled;
@property(readonly, nonatomic, getter=isSearchKitEnabled) _Bool searchKitEnabled;
@end

