//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPTFreeTierPlaylistPlaylistItemsViewModelDecorator.h"

#import "SPTPlayerObserver-Protocol.h"
#import "SPTShadowPlaylistURIResolverObserver-Protocol.h"

@class NSArray, NSString, SPTPlayerState, SPTPlaylistRouteImplementation, SPTShadowPlaylistURIResolver;
@protocol SPTClientSettings, SPTPlaylistPlatformPlaylistDataLoader;

@interface SPTShadowPlaylistItemsViewModel : SPTFreeTierPlaylistPlaylistItemsViewModelDecorator <SPTShadowPlaylistURIResolverObserver, SPTPlayerObserver>
{
    SPTPlaylistRouteImplementation *_route;
    id <SPTClientSettings> _clientSettings;
    id <SPTPlaylistPlatformPlaylistDataLoader> _playlistDataLoader;
    SPTPlayerState *_lastPlayerState;
    NSArray *_currentSorting;
    SPTShadowPlaylistURIResolver *_uriResolver;
    NSArray *_writePlaylistTracks;
    NSArray *_readPlaylistTracks;
}

@property(copy, nonatomic) NSArray *readPlaylistTracks; // @synthesize readPlaylistTracks=_readPlaylistTracks;
@property(copy, nonatomic) NSArray *writePlaylistTracks; // @synthesize writePlaylistTracks=_writePlaylistTracks;
@property(nonatomic) __weak SPTShadowPlaylistURIResolver *uriResolver; // @synthesize uriResolver=_uriResolver;
@property(copy, nonatomic) NSArray *currentSorting; // @synthesize currentSorting=_currentSorting;
@property(retain, nonatomic) SPTPlayerState *lastPlayerState; // @synthesize lastPlayerState=_lastPlayerState;
@property(retain, nonatomic) id <SPTPlaylistPlatformPlaylistDataLoader> playlistDataLoader; // @synthesize playlistDataLoader=_playlistDataLoader;
@property(retain, nonatomic) id <SPTClientSettings> clientSettings; // @synthesize clientSettings=_clientSettings;
@property(retain, nonatomic) SPTPlaylistRouteImplementation *route; // @synthesize route=_route;
- (void).cxx_destruct;
- (void)player:(id)arg1 stateDidChange:(id)arg2 fromState:(id)arg3;
- (void)updateTracks;
- (id)readPlaylistTracksForIndex:(long long)arg1;
- (id)trackViewModelAtIndex:(long long)arg1;
- (id)trackEntityAtIndex:(long long)arg1;
- (id)indexForRowId:(id)arg1;
- (void)uriResolver:(id)arg1 didRegenerateReadListForRoute:(id)arg2;
- (void)uriResolver:(id)arg1 didCreateShadow:(id)arg2;
- (id)sortingArrayFromSortingFiltering:(id)arg1;
- (void)freeTierPlaylistModel:(id)arg1 playlistModelEntityDidChange:(id)arg2;
- (id)initWithRoute:(id)arg1 playlistModel:(id)arg2 itemsViewModel:(id)arg3 clientSettings:(id)arg4 resolver:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

