//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSTimer, SPTDynamicSignupFlowController, SPTLoginDialogController, SPTLoginEmailValidationDialogLogger, SPTLoginSplitEmailSignupViewLogger, SPTSignupA11yEnvironment, SPTSignupDisplayNameSuggestionDataLoader, SPTSignupUserInfoModel, SPTSignupValidationSequencer;
@protocol SPTSignupEmailViewModelDelegate;

@interface SPTSignupEmailViewModel : NSObject
{
    _Bool _shouldEnableNextButton;
    _Bool _fullValidationEnabled;
    SPTLoginSplitEmailSignupViewLogger *_logger;
    id <SPTSignupEmailViewModelDelegate> _delegate;
    SPTSignupUserInfoModel *_userInfoModel;
    SPTSignupValidationSequencer *_validationSequencer;
    NSTimer *_timer;
    SPTLoginDialogController *_dialogController;
    SPTLoginEmailValidationDialogLogger *_dialogLogger;
    SPTSignupDisplayNameSuggestionDataLoader *_displayNameDataLoader;
    NSString *_lastValidEmail;
    SPTDynamicSignupFlowController *_flowController;
    SPTSignupA11yEnvironment *_a11yEnvironment;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) SPTSignupA11yEnvironment *a11yEnvironment; // @synthesize a11yEnvironment=_a11yEnvironment;
@property(readonly, nonatomic) SPTDynamicSignupFlowController *flowController; // @synthesize flowController=_flowController;
@property(copy, nonatomic) NSString *lastValidEmail; // @synthesize lastValidEmail=_lastValidEmail;
@property(readonly, nonatomic) SPTSignupDisplayNameSuggestionDataLoader *displayNameDataLoader; // @synthesize displayNameDataLoader=_displayNameDataLoader;
@property(readonly, nonatomic) SPTLoginEmailValidationDialogLogger *dialogLogger; // @synthesize dialogLogger=_dialogLogger;
@property(readonly, nonatomic) SPTLoginDialogController *dialogController; // @synthesize dialogController=_dialogController;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic, getter=isFullValidationEnabled) _Bool fullValidationEnabled; // @synthesize fullValidationEnabled=_fullValidationEnabled;
@property(readonly, nonatomic) SPTSignupValidationSequencer *validationSequencer; // @synthesize validationSequencer=_validationSequencer;
@property(readonly, nonatomic) SPTSignupUserInfoModel *userInfoModel; // @synthesize userInfoModel=_userInfoModel;
@property(nonatomic) _Bool shouldEnableNextButton; // @synthesize shouldEnableNextButton=_shouldEnableNextButton;
@property(nonatomic) __weak id <SPTSignupEmailViewModelDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SPTLoginSplitEmailSignupViewLogger *logger; // @synthesize logger=_logger;
- (void)presentPopupForVoiceOverUserWithError:(id)arg1;
- (void)presentEmailExistsPopupWithEmail:(id)arg1;
- (void)navigateToNextScreenWithEmail:(id)arg1;
- (void)performFinalValidationWithValue:(id)arg1;
- (void)userDidTapNextButtonWithValue:(id)arg1;
- (void)userDidTapReturnButtonWithValue:(id)arg1;
- (void)userDidUpdateTextFieldWithValue:(id)arg1;
- (id)nextButtonText;
- (id)fieldDisclosureLabelText;
- (id)fieldAccessibilityLabel;
- (id)fieldTitleLabelText;
- (id)titleLabelText;
@property(readonly, nonatomic) _Bool shouldAutoFocusTextFieldOnAppear;
- (id)initWithLogger:(id)arg1 userInfoModel:(id)arg2 validationSequencer:(id)arg3 displayNameDataLoader:(id)arg4 dialogController:(id)arg5 dialogLogger:(id)arg6 flowController:(id)arg7 a11yEnvironment:(id)arg8;

@end

