//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, SPTSharingSDKImageDownloader, SPTSharingSDKLinkGenerator;
@protocol SPTSharingSDKDeeplinkHandler, SPTSharingSDKNetworkService, SPTSharingSDKShareDialogPresenter, SPTSharingSDKShareHandler;

@interface SPTSharingSDK : NSObject
{
    SPTSharingSDKImageDownloader *_imageDownloader;
    SPTSharingSDKLinkGenerator *_linkGenerator;
    NSArray *_allShareDestinations;
    id <SPTSharingSDKDeeplinkHandler> _deeplinkHandler;
    id <SPTSharingSDKShareDialogPresenter> _dialogPresenter;
    id <SPTSharingSDKNetworkService> _networkService;
    id <SPTSharingSDKShareHandler> _shareHandler;
}

+ (id)notImplementedError;
- (void).cxx_destruct;
@property(retain, nonatomic) id <SPTSharingSDKShareHandler> shareHandler; // @synthesize shareHandler=_shareHandler;
@property(readonly, nonatomic) id <SPTSharingSDKNetworkService> networkService; // @synthesize networkService=_networkService;
@property(readonly, nonatomic) id <SPTSharingSDKShareDialogPresenter> dialogPresenter; // @synthesize dialogPresenter=_dialogPresenter;
@property(readonly, nonatomic) id <SPTSharingSDKDeeplinkHandler> deeplinkHandler; // @synthesize deeplinkHandler=_deeplinkHandler;
@property(readonly, nonatomic) NSArray *allShareDestinations; // @synthesize allShareDestinations=_allShareDestinations;
- (id)provideStoriesShareHandlerWithDestination:(id)arg1 entityData:(id)arg2;
- (id)provideMessageShareHandlerWithDestination:(id)arg1 entityData:(id)arg2 contextViewController:(id)arg3;
- (id)provideLinkShareHandlerWithDestination:(id)arg1 entityData:(id)arg2 contextViewController:(id)arg3;
- (id)provideDownloadShareHandlerWithEntityData:(id)arg1;
- (id)buildShareHandlerFromShareDestination:(id)arg1 shareEntityData:(id)arg2 contextViewController:(id)arg3;
- (void)generateShareableURLWithPayload:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)performShareToDestination:(id)arg1 withShareEntityData:(id)arg2 contextViewController:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)provideShareEntityDataFactory;
- (id)provideShareDestinationByID:(id)arg1;
- (id)provideAvailableShareDestinations;
@property(readonly, nonatomic) SPTSharingSDKLinkGenerator *linkGenerator; // @synthesize linkGenerator=_linkGenerator;
@property(readonly, nonatomic) SPTSharingSDKImageDownloader *imageDownloader; // @synthesize imageDownloader=_imageDownloader;
- (id)initWithNetworkService:(id)arg1 deeplinkHandler:(id)arg2 dialogPresenter:(id)arg3;

@end

