//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SFSafariViewControllerDelegate-Protocol.h"
#import "SPTSignupTermsAndPolicyManagerDelegate-Protocol.h"
#import "SPTSignupTermsAndPolicyViewDelegate-Protocol.h"

@class NSString, SPTSignupTermsAndPolicyCopyProvider, SPTSignupTermsAndPolicyManager, SPTSignupTermsAndPolicyViewStyle;
@protocol SPTLoginLogger, SPTSignupTermsAndPolicyViewModelDelegate;

@interface SPTSignupTermsAndPolicyViewModel : NSObject <SPTSignupTermsAndPolicyManagerDelegate, SFSafariViewControllerDelegate, SPTSignupTermsAndPolicyViewDelegate>
{
    id <SPTSignupTermsAndPolicyViewModelDelegate> _delegate;
    SPTSignupTermsAndPolicyManager *_termsAndPolicyManager;
    SPTSignupTermsAndPolicyViewStyle *_style;
    id <SPTLoginLogger> _logger;
    SPTSignupTermsAndPolicyCopyProvider *_termsAndPolicyMessageProvider;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) SPTSignupTermsAndPolicyCopyProvider *termsAndPolicyMessageProvider; // @synthesize termsAndPolicyMessageProvider=_termsAndPolicyMessageProvider;
@property(retain, nonatomic) id <SPTLoginLogger> logger; // @synthesize logger=_logger;
@property(retain, nonatomic) SPTSignupTermsAndPolicyViewStyle *style; // @synthesize style=_style;
@property(retain, nonatomic) SPTSignupTermsAndPolicyManager *termsAndPolicyManager; // @synthesize termsAndPolicyManager=_termsAndPolicyManager;
@property(nonatomic) __weak id <SPTSignupTermsAndPolicyViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void)safariViewControllerDidFinish:(id)arg1;
- (void)userDidTapLegalLinkWithURL:(id)arg1;
- (void)showTermsAndPolicyDialog;
- (void)termsAndPolicyManagerDidAcceptAllLicences:(id)arg1;
- (void)termsAndPolicyManagerDidSelectPrivacyAndPolicyDetails:(id)arg1;
- (void)termsAndPolicyManagerDidSelectTermsAndConditionsDetails:(id)arg1;
- (void)logUserDidTapLinkWith:(id)arg1;
- (void)presentTermsDetailsForURL:(id)arg1;
- (_Bool)isTermsAndPolicyDialogRequired;
- (id)termsAndConditionsAttributedTextWithStyle:(id)arg1;
- (id)initWithTermsAndPolicyManager:(id)arg1 logger:(id)arg2 termsCopyProvider:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

