//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPTSharingSDKStoriesShareHandler.h"

@class SPTSharingSDKImageDownloader, SPTSharingSDKLinkGenerator;
@protocol SPTSharingSDKDeeplinkHandler, SPTSharingSDKEntityData, SPTSharingSDKPasteboardHandler;

@interface SPTSharingSDKFacebookStoriesShareHandler : SPTSharingSDKStoriesShareHandler
{
    id <SPTSharingSDKEntityData> _entityData;
    SPTSharingSDKImageDownloader *_imageDownloader;
    SPTSharingSDKLinkGenerator *_linkGenerator;
    id <SPTSharingSDKDeeplinkHandler> _deeplinkHandler;
    id <SPTSharingSDKPasteboardHandler> _pasteboardHandler;
}

- (void).cxx_destruct;
- (id)pasteboardHandler;
- (id)deeplinkHandler;
- (id)linkGenerator;
- (id)imageDownloader;
- (id)entityData;
- (id)deeplinkScheme;
- (id)deeplinkHost;
- (id)pasteboardStickerImageKey;
- (id)pasteboardContentURLKey;
- (id)extraPasteboardItems;
- (id)stickerImagePath;
- (id)pasteboardBottomColorKey;
- (id)pasteboardTopColorKey;
- (_Bool)shouldUseDefaultGradientColors;
- (id)initWithEntityData:(id)arg1 linkGenerator:(id)arg2 imageDownloader:(id)arg3 deeplinkHandler:(id)arg4 pasteboardHandler:(id)arg5;

@end

