//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSSet, NSString, NSUUID;

@interface SPTTimeMeasurement : NSObject
{
    // Error parsing type: , name: measurementId
    // Error parsing type: , name: category
    // Error parsing type: , name: dimensions
    // Error parsing type: , name: metadata
    // Error parsing type: , name: points
    // Error parsing type: , name: featureId
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *featureId;
@property(nonatomic, readonly) NSSet *points;
@property(nonatomic, readonly) NSDictionary *metadata;
@property(nonatomic, readonly) NSDictionary *dimensions;
@property(nonatomic, readonly) NSString *category;
@property(nonatomic, readonly) NSUUID *measurementId;

@end

