//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTUBIMobileBrowseEventFactory-Protocol.h"

@class NSArray, NSString;

@interface SPTUBIMobileBrowseEventFactoryImplementation : NSObject <SPTUBIMobileBrowseEventFactory>
{
    NSArray *_components;
}

+ (id)factory;
- (void).cxx_destruct;
@property(copy, nonatomic) NSArray *components; // @synthesize components=_components;
- (id)retryButtonFactory;
- (id)promotionFactoryWithIdentifier:(id)arg1 uri:(id)arg2 reason:(id)arg3;
- (id)carouselFactoryWithIdentifier:(id)arg1 position:(long long)arg2 reason:(id)arg3;
- (id)listFactoryWithIdentifier:(id)arg1 position:(long long)arg2 reason:(id)arg3;
- (id)gridFactoryWithIdentifier:(id)arg1 position:(long long)arg2 reason:(id)arg3;
- (id)pageHeaderFactoryWithIdentifier:(id)arg1 uri:(id)arg2 reason:(id)arg3;
- (id)_location;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

