//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTUBIMobileArtistPageEventFactory-Protocol.h"

@class NSArray, NSString;

@interface SPTUBIMobileArtistPageEventFactoryImplementation : NSObject <SPTUBIMobileArtistPageEventFactory>
{
    NSArray *_components;
}

+ (id)factory;
- (void).cxx_destruct;
@property(copy, nonatomic) NSArray *components; // @synthesize components=_components;
- (id)biographyFactory;
- (id)concertsFactory;
- (id)merchFactory;
- (id)artistFanFundingFactory;
- (id)artistsPlaylistFactory;
- (id)fansAlsoLikeFactory;
- (id)featuringFactory;
- (id)popularReleasesFactory;
- (id)artistPickFactory;
- (id)trackCloudFactory;
- (id)topTracksFactory;
- (id)likedTracksFactoryWithUri:(id)arg1;
- (id)headerFactory;
- (id)_location;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

