//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPTService-Protocol.h"

@protocol SPTUserBehaviourInstrumentation, SPTUserBehaviourInstrumentationNavigationObserver;

@protocol SPTUserBehaviourInstrumentationService <SPTService>
- (void)removeObserver:(id <SPTUserBehaviourInstrumentationNavigationObserver>)arg1;
- (void)addObserver:(id <SPTUserBehaviourInstrumentationNavigationObserver>)arg1;
- (id <SPTUserBehaviourInstrumentation>)provideUserBehaviourInstrumentation;
@end

