//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class SPTVoiceNowPlayingView, SPTVoiceNowPlayingViewModel;
@protocol GLUEImageLoader;

@interface SPTVoiceNowPlayingViewController : UIViewController
{
    id <GLUEImageLoader> _glueImageLoader;
    SPTVoiceNowPlayingViewModel *_nowPlayingViewModel;
    SPTVoiceNowPlayingView *_nowPlayingContainerView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SPTVoiceNowPlayingView *nowPlayingContainerView; // @synthesize nowPlayingContainerView=_nowPlayingContainerView;
@property(readonly, nonatomic) SPTVoiceNowPlayingViewModel *nowPlayingViewModel; // @synthesize nowPlayingViewModel=_nowPlayingViewModel;
@property(readonly, nonatomic) id <GLUEImageLoader> glueImageLoader; // @synthesize glueImageLoader=_glueImageLoader;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithViewModel:(id)arg1 glueImageLoader:(id)arg2;

@end

