//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTVoiceDeeplinkURIResolver-Protocol.h"

@class NSString;
@protocol SPTEntityService, SPTPodcastEntityDataLoader;

@interface SPTVoiceDeeplinkURIResolverImplementation : NSObject <SPTVoiceDeeplinkURIResolver>
{
    id <SPTEntityService> _entityService;
    id <SPTPodcastEntityDataLoader> _podcastEntityDataLoader;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <SPTPodcastEntityDataLoader> podcastEntityDataLoader; // @synthesize podcastEntityDataLoader=_podcastEntityDataLoader;
@property(readonly, nonatomic) id <SPTEntityService> entityService; // @synthesize entityService=_entityService;
- (void)resolveDeeplinkWithCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)initWithEntityService:(id)arg1 podcastEntityDataLoader:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

