//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTVideoPlaybackSessionAssetLoader-Protocol.h"

@class AVContentKeySession, BMAVFactory, BMContentDownloader, NSString;
@protocol SPTVideoResourceLoaderInternal;

@interface SPTVideoPlaybackSessionAssetLoader : NSObject <SPTVideoPlaybackSessionAssetLoader>
{
    BMAVFactory *_avFactory;
    BMContentDownloader *_contentDownloader;
    id <SPTVideoResourceLoaderInternal> _resourceLoader;
    AVContentKeySession *_contentKeySession;
}

- (void).cxx_destruct;
@property(retain, nonatomic) AVContentKeySession *contentKeySession; // @synthesize contentKeySession=_contentKeySession;
@property(retain, nonatomic) id <SPTVideoResourceLoaderInternal> resourceLoader; // @synthesize resourceLoader=_resourceLoader;
@property(retain, nonatomic) BMContentDownloader *contentDownloader; // @synthesize contentDownloader=_contentDownloader;
@property(retain, nonatomic) BMAVFactory *avFactory; // @synthesize avFactory=_avFactory;
- (void)prepareAsset:(id)arg1 withKeys:(id)arg2 completion:(CDUnknownBlockType)arg3 errorHandler:(CDUnknownBlockType)arg4;
- (void)loadPlayerItemWithCompletion:(CDUnknownBlockType)arg1 errorHandler:(CDUnknownBlockType)arg2;
- (id)initWithAVFactory:(id)arg1 contentDownloader:(id)arg2 resourceLoader:(id)arg3 contentKeySession:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

