//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SPTVideoCoordinatorCosmosSender;
@protocol BMBetamaxPlayer, BMPlaybackTimeObservable;

@interface SPTVideoCoordinatorPlayerInterruptor : NSObject
{
    id <BMPlaybackTimeObservable> _timeObservable;
    double _interruptionPosition;
    double _mediaDuration;
    id <BMBetamaxPlayer> _player;
    SPTVideoCoordinatorCosmosSender *_cosmosSender;
}

@property(retain, nonatomic) SPTVideoCoordinatorCosmosSender *cosmosSender; // @synthesize cosmosSender=_cosmosSender;
@property(retain, nonatomic) id <BMBetamaxPlayer> player; // @synthesize player=_player;
@property(nonatomic) double mediaDuration; // @synthesize mediaDuration=_mediaDuration;
@property(nonatomic) double interruptionPosition; // @synthesize interruptionPosition=_interruptionPosition;
@property(retain, nonatomic) id <BMPlaybackTimeObservable> timeObservable; // @synthesize timeObservable=_timeObservable;
- (void).cxx_destruct;
- (void)scheduleInterruption;
- (_Bool)canScheduleInterruption;
- (id)initWithPlayer:(id)arg1 cosmosSender:(id)arg2;

@end

