//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SPTConnectivityAccessTokenScope;

@interface SPTWebGate : NSObject
{
    NSString *_host;
    SPTConnectivityAccessTokenScope *_accessTokenScope;
}

@property(readonly, nonatomic) SPTConnectivityAccessTokenScope *accessTokenScope; // @synthesize accessTokenScope=_accessTokenScope;
@property(readonly, nonatomic) NSString *host; // @synthesize host=_host;
- (void).cxx_destruct;
- (id)callForRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (id)initWithAccessTokenScope:(id)arg1 withHostNameOverride:(id)arg2;
- (id)initWithAccessTokenScope:(id)arg1;

@end

