//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTYourLibraryTestManager-Protocol.h"

@class NSString;
@protocol _TtP19YourLibraryXFeature26SPTYourLibraryXTestManager_, _TtP22YourLibraryBetaFeature29SPTYourLibraryBetaTestManager_;

@interface SPTYourLibraryTestManagerImplementation : NSObject <SPTYourLibraryTestManager>
{
    id <_TtP19YourLibraryXFeature26SPTYourLibraryXTestManager_> _yourLibraryXTestManager;
    id <_TtP22YourLibraryBetaFeature29SPTYourLibraryBetaTestManager_> _yourLibraryBetaTestManager;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <_TtP22YourLibraryBetaFeature29SPTYourLibraryBetaTestManager_> yourLibraryBetaTestManager; // @synthesize yourLibraryBetaTestManager=_yourLibraryBetaTestManager;
@property(readonly, nonatomic) id <_TtP19YourLibraryXFeature26SPTYourLibraryXTestManager_> yourLibraryXTestManager; // @synthesize yourLibraryXTestManager=_yourLibraryXTestManager;
@property(readonly, nonatomic, getter=isYourLibraryBetaEnabled) _Bool yourLibraryBetaEnabled;
@property(readonly, nonatomic, getter=isYourLibraryXEnabled) _Bool yourLibraryXEnabled;
- (id)initWithYourLibraryXTestManager:(id)arg1 yourLibraryBetaTestManager:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

