//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPTYourLibraryMusicRangeDataSource-Protocol.h"

@class NSArray, SPTPlayOptions;
@protocol SPTPlayer, SPTYourLibraryMusicLikedSongsExternalFilterModelDelegate;

@protocol SPTYourLibraryMusicLikedSongsExternalFilterModel <SPTYourLibraryMusicRangeDataSource>
@property(readonly, nonatomic, getter=isLoaded) _Bool loaded;
@property(nonatomic) __weak id <SPTYourLibraryMusicLikedSongsExternalFilterModelDelegate> externalFilterDelegate;
- (void)playWithPlayer:(id <SPTPlayer>)arg1 playOptions:(SPTPlayOptions *)arg2 filterRules:(NSArray *)arg3;
- (_Bool)isManagingFilterRules:(NSArray *)arg1;
- (void)loadModel;
@end

