//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTDataLoaderDelegate-Protocol.h"
#import "SPTYourLibraryMusicLikedSongsExternalFilterModel-Protocol.h"

@class NSArray, NSString, SPTDataLoader;
@protocol SPTCollectionPlatform, SPTCollectionPlatformDataLoader, SPTDataLoaderAuthorisationHostRegistration, SPTYourLibraryMusicLikedSongsExternalFilterModelDelegate, SPTYourLibraryMusicRangeDataSourceDelegate, SPTYourLibraryMusicTestManager;

@interface SPTYourLibraryMusicLikedSongsDescriptorsModel : NSObject <SPTDataLoaderDelegate, SPTYourLibraryMusicLikedSongsExternalFilterModel>
{
    _Bool _loaded;
    id <SPTYourLibraryMusicLikedSongsExternalFilterModelDelegate> externalFilterDelegate;
    id <SPTYourLibraryMusicRangeDataSourceDelegate> delegate;
    NSArray *sectionIndices;
    SPTDataLoader *_dataLoader;
    id <SPTCollectionPlatform> _collectionPlatform;
    id <SPTCollectionPlatformDataLoader> _collectionPlatformDataLoader;
    id <SPTDataLoaderAuthorisationHostRegistration> _authorizer;
    id <SPTYourLibraryMusicTestManager> _testManager;
    NSArray *_trackURLs;
    NSArray *_trackDescriptors;
    NSArray *_currentTracks;
    NSArray *_staticDescriptors;
}

+ (id)commonDescriptorsURL;
+ (id)descriptorsURLWithTrackURLs:(id)arg1;
@property(copy, nonatomic) NSArray *staticDescriptors; // @synthesize staticDescriptors=_staticDescriptors;
@property(copy, nonatomic) NSArray *currentTracks; // @synthesize currentTracks=_currentTracks;
@property(copy, nonatomic) NSArray *trackDescriptors; // @synthesize trackDescriptors=_trackDescriptors;
@property(copy, nonatomic) NSArray *trackURLs; // @synthesize trackURLs=_trackURLs;
@property(nonatomic, getter=isLoaded) _Bool loaded; // @synthesize loaded=_loaded;
@property(readonly, nonatomic) id <SPTYourLibraryMusicTestManager> testManager; // @synthesize testManager=_testManager;
@property(readonly, nonatomic) id <SPTDataLoaderAuthorisationHostRegistration> authorizer; // @synthesize authorizer=_authorizer;
@property(readonly, nonatomic) id <SPTCollectionPlatformDataLoader> collectionPlatformDataLoader; // @synthesize collectionPlatformDataLoader=_collectionPlatformDataLoader;
@property(readonly, nonatomic) id <SPTCollectionPlatform> collectionPlatform; // @synthesize collectionPlatform=_collectionPlatform;
@property(readonly, nonatomic) SPTDataLoader *dataLoader; // @synthesize dataLoader=_dataLoader;
@property(readonly, nonatomic) NSArray *sectionIndices; // @synthesize sectionIndices;
@property(nonatomic) __weak id <SPTYourLibraryMusicRangeDataSourceDelegate> delegate; // @synthesize delegate;
@property(nonatomic) __weak id <SPTYourLibraryMusicLikedSongsExternalFilterModelDelegate> externalFilterDelegate; // @synthesize externalFilterDelegate;
- (void).cxx_destruct;
- (void)unregisterInternalWebgate;
- (void)registerInternalWebgate;
- (void)loadTrackDescriptorsWithBatchOffset:(unsigned long long)arg1;
- (void)loadCommonDescriptors;
- (void)loadStaticDescriptors;
- (void)trackDescriptorLoadingCompleted;
- (void)updateTaggedSongsWithResponseDictionary:(id)arg1;
- (void)notifyFilterRulesChangedWithDescriptors:(id)arg1;
- (void)updateTagFilterRulesWithResponseDictionary:(id)arg1;
- (void)dataLoader:(id)arg1 didReceiveSuccessfulResponse:(id)arg2;
- (void)dataLoader:(id)arg1 didReceiveErrorResponse:(id)arg2;
@property(readonly, nonatomic) long long totalNumberOfItems;
- (void)willDisplayItemAIndex:(long long)arg1;
- (id)peekItemAtIndexPath:(id)arg1;
- (id)trackUrlsWithFilterRules:(id)arg1;
- (void)loadWithSortRules:(id)arg1 filterRules:(id)arg2 textFilter:(id)arg3;
- (id)itemAtIndexPath:(id)arg1;
- (void)playWithPlayer:(id)arg1 playOptions:(id)arg2 filterRules:(id)arg3;
- (_Bool)isManagingFilterRules:(id)arg1;
- (void)loadModel;
- (void)dealloc;
- (id)initWithCollectionPlatform:(id)arg1 dataLoader:(id)arg2 authorizer:(id)arg3 testManager:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

