//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPTYourLibraryMusicPlaylistsModelEntity-Protocol.h"

@class NSArray, NSString;
@protocol SPTYourLibraryMusicPlaylistModelItemEntity;

@interface SPTYourLibraryMusicPlaylistsModelEntityImplementation : NSObject <SPTYourLibraryMusicPlaylistsModelEntity>
{
    _Bool _hasHiddenContent;
    NSArray *_items;
    id <SPTYourLibraryMusicPlaylistModelItemEntity> _favoriteEntity;
    id <SPTYourLibraryMusicPlaylistModelItemEntity> _offlineMixEntity;
    NSArray *_sectionIndexes;
    NSArray *_sectionTitles;
    NSArray *_itemFilters;
}

@property(copy, nonatomic) NSArray *itemFilters; // @synthesize itemFilters=_itemFilters;
@property(copy, nonatomic) NSArray *sectionTitles; // @synthesize sectionTitles=_sectionTitles;
@property(copy, nonatomic) NSArray *sectionIndexes; // @synthesize sectionIndexes=_sectionIndexes;
@property(retain, nonatomic) id <SPTYourLibraryMusicPlaylistModelItemEntity> offlineMixEntity; // @synthesize offlineMixEntity=_offlineMixEntity;
@property(retain, nonatomic) id <SPTYourLibraryMusicPlaylistModelItemEntity> favoriteEntity; // @synthesize favoriteEntity=_favoriteEntity;
@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) _Bool hasHiddenContent; // @synthesize hasHiddenContent=_hasHiddenContent;
- (void).cxx_destruct;
- (_Bool)shouldAddEntity:(id)arg1;
- (void)setUpItemsWithPlaylistFolderItems:(id)arg1 onDemandSet:(id)arg2;
- (void)setUpOfflineMix:(id)arg1 onDemandSet:(id)arg2;
- (void)setUpFavoriteMix:(id)arg1;
- (id)initWithPlaylistFolderItems:(id)arg1 favoriteMixEntity:(id)arg2 offlineMixEntity:(id)arg3 onDemandSet:(id)arg4 itemFilters:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

